package com.pay10.commons.user;

public enum UserType {
	SUPERADMIN, SUBSUPERADMIN, ADMIN, MERCHANT, BUYER, ACQUIRER,POSMERCHANT,SUBUSER,RESELLER,SUBADMIN,SUBACQUIRER,ASSOCIATE,AGENT,SUPERMERCHANT,SMA,MA,
	Agent
}
