name: Build and Deploy

on:
  push:
    branches:
      - main  # Adjust to your main branch name

env:
  GITLAB_REPO_URL: "https://github.com/sahilk020/artemis-main-bp-admin.git"
  S3_BUCKET: "pereprod.sahiltest"
  AWS_REGION: "eu-central-1"
  CICD_RELEASES: "/opt/cicd-releases"
  COMPONENT_DIR: "pay10-pg-ws"
  BUILD_COMMAND: "clean bootWar -x test"

jobs:
  build:
    runs-on: ubuntu-latest  # Using the default Ubuntu runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Amazon Linux 2 Docker
        uses: docker://amazonlinux:2
        with:
          args: |
            /bin/bash -c '
            echo "Installing necessary dependencies"
            yum install -y git aws-cli java-1.8.0-openjdk-devel

            # Set the Date And Time
            DATE_TIME=$(TZ="Asia/Kolkata" date +"%Y%m%d_%H%M%S")
            echo "DATE_TIME=${DATE_TIME}" >> $GITHUB_ENV
            
            echo "Cloning the repository from GitHub"
            git clone -b main $GITLAB_REPO_URL /opt/code
            
            echo "Building the component"
            cd /opt/code/$COMPONENT_DIR
            chmod +x gradlew
            ./gradlew $BUILD_COMMAND
            
            mkdir -p $CICD_RELEASES/${DATE_TIME}
            mv build/libs/*.war $CICD_RELEASES/${DATE_TIME}/
            echo "Preparing and uploading WAR file to S3"
            aws s3 cp $CICD_RELEASES/${DATE_TIME} s3://$S3_BUCKET/cicd-releases/pgws/${DATE_TIME}/ --region $AWS_REGION --recursive
            '

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: codeBuildArtifacts
          path: |
            /opt/cicd-releases/*
