version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo "Installing necessary dependencies..."
      - yum install -y wget git
      - echo "Updating the package system..."
      - dnf update -y
      - echo "Installing Amazon Corretto 8..."
      - dnf install -y java-1.8.0-amazon-corretto.x86_64
      - echo "Checking Java installation..."
      - java -version
      - export JAVA_HOME=/usr/lib/jvm/java-1.8.0-amazon-corretto.x86_64/jre
      - echo "JAVA_HOME is set to $JAVA_HOME"
      - echo "Cloning the Git repository..."
      - mkdir -p /sahil/git
      - git clone https://github.com/sahilk020/artemis-main-bp-admin.git /sahil/git/artemis-main-bp-admin
      - echo "Downloading and installing Apache Tomcat..."
      - cd /tmp
      - wget https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.23/bin/apache-tomcat-10.0.23.tar.gz
      - tar -xvf apache-tomcat-10*.tar.gz
      - sudo mv apache-tomcat-10.0.23 /opt/tomcat
      - sudo chown -R root:root /opt/tomcat
      - /opt/tomcat/bin/startup.sh
      - echo "Tomcat 10 installed and started successfully in /opt/tomcat!"

  pre_build:
    commands:
      - echo "Preparing to build components..."
      - echo "Building and deploying components..."
      - export COMPONENTS=("crm" "crypto" "bindb" "pgui" "email" "sms" "batch" "pgws" "crmws" "mobile" "si")
      - export COMPONENT_DIRECTORIES=("pay10-crm" "pay10-crypto" "pay10-bindb" "pay10-pg-ui" "pay10-notification-email" "pay10-notification-sms" "pay10-batchProcessor" "pay10-pg-ws" "pay10-crm-ws" "pay10-mobile")
      - export COMPONENT_COMMANDS=("clean build -x test" "clean bootWar -x test" "clean build -x test" "clean bootWar -x test" "clean bootWar -x test" "clean bootWar -x test" "clean build -x test" "clean bootWar -x test" "clean build -x test" "clean bootWar -x test")
      - echo "Sleeping for 600 seconds to allow services to stabilize..."
      
      

  build:
    commands:
      - echo "Finding artemis-main-bp-admin location..."
      - artemis_dir=$(find /codebuild/output/src*/ -name "artemis-main-bp-admin" -type d | head -n 1)
      - if [[ -z "$artemis_dir" ]]; then echo "Error:artemis-main-bp-admin directory not found!"; exit 1; fi
      - echo "Found artemis-main-bp-admin at $artemis_dir"
      - echo "Copying artemis-main-bp-admin to /home/sahil/"
      - sudo cp -r "$artemis_dir" /home/sahil/

      - echo "Building components..."
      - |
        for index in ${!COMPONENTS[@]}; do
          component=${COMPONENTS[$index]}
          componentDirectory=${COMPONENT_DIRECTORIES[$index]}
          buildCommand=${COMPONENT_COMMANDS[$index]}

          echo "Building and deploying $component component in $componentDirectory"

          sudo mkdir -p /sahil/build/$componentDirectory
          cd /sahil/build/$componentDirectory || { echo "Failed to change directory to /sahil/build/$componentDirectory"; exit 1; }

          gradlewPath="/sahil/artemis-main-bp-admin/$componentDirectory/"
          wrapperJarPath="/sahil/artemis-main-bp-admin/$componentDirectory/gradle/wrapper/"

          echo "Copying gradlew and wrapper files to the current directory"
          sudo cp "$gradlewPath" .
          sudo cp "$wrapperJarPath" "gradle/wrapper/"
          sudo chmod +x gradlew

          if ! JAVA_HOME=$JAVA_HOME ./gradlew $buildCommand; then
            echo "Gradle build failed for $component. Please check the logs for details."
            exit 1
          fi
        done

      - sudo mkdir -p /sahil/artifacts
      - sudo mv /sahil/build/*/build/libs/* /sahil/artifacts/ || echo "Warning:No artifacts found to move."

  post_build:
    commands:
      - if [ -d "/home/sahil/cicd_release/" ]; then
          echo "Checking for release directories in /home/sahil/cicd_release/"
          sudo ls -l /home/sahil/cicd_release/ || echo "No release directories found."
          latestDir=$(sudo ls -td /home/sahil/cicd_release/*/ 2>/dev/null | head -n 1)
        else
          echo "No release directories found in /home/sahil/cicd_release/"
          exit 0
        fi

      - if [ -z "$latestDir" ]; then
          echo "No release directories found in /home/sahil/cicd_release/"
          exit 0
        fi

      - warFiles=$(sudo ls "$latestDir"/*.war 2>/dev/null)

      - if [ -z "$warFiles" ]; then
          echo "No WAR files found in the latest directory."
          exit 0
        fi

      - currentDate=$(date +'%Y%m%d_%H%M%S')
      - backupDir="/home/tom_backup/$currentDate"
      - sudo mkdir -p "$backupDir"

      - for warFile in $warFiles; do
          warFileName=$(basename "$warFile")
          sudo cp -r "/opt/tomcat/webapps/$warFileName" "$backupDir/$warFileName"
        done

artifacts:
  files:
    - /sahil/artifacts/**
