version: 0.2

env:
  variables:
    GITLAB_REPO_URL: "https://github.com/sahilk020/artemis-main-bp-admin.git"
    S3_BUCKET: "pereprod.sahiltest"
    AWS_REGION: "eu-central-1"
    CICD_RELEASES: "/opt/cicd-releases"
    COMPONENT_DIR: "pay10-pg-ws"
    BUILD_COMMAND: "clean bootWar -x test"

phases:
  install:
    commands:
      - echo "Installing necessary dependencies"
      - yum install -y git aws-cli
      - yum install -y java-1.8.0-openjdk-devel  # Ensure Java 8 is installed

  pre_build:
    commands:
      - echo "Cloning the repository"
      - git clone $GITLAB_REPO_URL /opt/code

  build:
    commands:
      - echo "Building the project"
      - cd /opt/code/$COMPONENT_DIR
      - chmod +x gradlew
      - ./gradlew $BUILD_COMMAND

  post_build:
    commands:
      - echo "Preparing to upload to S3"
      - mkdir -p ${CICD_RELEASES}/$(date +"%Y%m%d_%H%M%S")
      - mv build/libs/*.war ${CICD_RELEASES}/$(date +"%Y%m%d_%H%M%S")/ || echo "No WAR files found, skipping upload."

artifacts:
  files:
    - ${CICD_RELEASES}/*
