package com.pay10.commons.util;

/**
 * @author Sunil
 *
 */
public enum Constants {

	CRM_LOG_USER_PREFIX	("userId"),
	CRM_LOG_PREFIX		("CRM~"),
	PG_LOG_PREFIX		("PG~"),
	CARD_STARS			("************"),
	COMMA				(" , "),
	EQUATOR				("="),
	SEPARATOR			("~"),
	TXN_WS_PAYMENTEDGE_PROCESSOR				    ("TransactionWSPaymentEdgeProcessor"),

	AUTO_REFUND						("AutoRefund"), //add by abhi
	MAX_NUMBER_OF_KEYS	("100"),
	TRUE 				("1"),
	FALSE				("0"),
	FIELDS				("FIELDS"),
	TRANSACTIONSTATE_N	("INVALID REQUEST"),
	LAST_LOGIN          ("LAST_LOGIN"),
	LAST_LOGIN_IP       ("LAST_LOGIN_IP"),
	LAST_LOGIN_STATUS   ("LAST_LOGIN_STATUS"),
	USER				("USER"),
	USERTYPE			("USER_TYPE"),
	SALT_LENGTH         ("16"),
	BLANK_REPLACEMENT_STRING  (""),
	SALT_FILE_PATH_NAME ("salt.properties"),
	KEYSALT_FILE_PATH_NAME ("keysalt.properties"),
	PAYMENT_TYPE		("PAYMENT_TYPE"),
	PAYMENT_TYPE_MOP 	("PAYMENT_TYPE_MOP"),
	CARD_PAYMENT_TYPE_MOP 	("CARD_PAYMENT_TYPE_MOP"),
	TOKEN 				("TOKEN"),
	EXPRESS_PAY_FLAG	("EXPRESS_PAY_FLAG"),
	DIRECPAY_SEPARATOR  ("|"),
	YESBANK_SEPARATOR   ("&"),
	KOTAK_SEPARATOR   	("|"),
	CUSTOM_TOKEN  		("customToken"),
	QUOTES  			("'"),
	AMEX_SEPARATOR		("&"),
	IFRAME_PAYMENT_PAGE ("IFRAME_PAYMENT_PAGE"),
	TRANSACTION_COMPLETE_FLAG   ("INTERNAL_TXN_COMPLETE_FLAG"),
	Y_FLAG                      ("Y"),
	N_FLAG                      ("N"),
	USER_PERMISSION   	        ("USER_PERMISSION"),
	RETRY_COUNT                 ("RETRY_COUNT"),
	RETRY_MESSAGE                 ("RETRY_MESSAGE"),
	RUPAY_RETURN_URL_NAME       ("RupayReturnUrl"),
	Y ("Y"),
	BILLING_COLLECTION  		("billingDetails"),
	HIBERNATE_FILE_NAME			("hibernate.cfg.xml"),
	AXIS_UPI_KEY				("axisUpiKey.txt"),
	SERVER_ID					("PG_SERVER_ID"),
	DEFAULT_CURRENCY_CODE       ("356"),
	ACCESSIBLE_ACTION	("ACCESSIBLE_ACTION"),
	ACCESSIBLE_MENUS 	("ACCESSIBLE_MENUS"),
	ACCESSIBLE_MENUS_JSON 	("ACCESSIBLE_MENUS_JSON"),
	ACCESSIBLE_PERMISSION 	("ACCESSIBLE_PERMISSION"),
	ACTION_MESSAGE_BY_ACTION 	("ACTION_MESSAGE_BY_ACTION"),
	SEGMENT					("SEGMENT"),
	TXN_WS_CITYUNIONBANK_PROCESSOR		("TransactionWSCityUnionBankNBProcessor"),

	//internal service constants
	INTERNAL_WEBSERVICE_ALLOWED_IP  ("InternalWebserviceAllowedIP"),
	ALLOW							("allow"),
	INTERNAL_WEBSERVICE_URL         ("/process/payment"),
	INTERNAL_WEBSERVICE_FILTER_NAME ("remoteAddressFilter"),

	//Acquirer Supported MOP
	CITRUS_NETBANKING_SUPPORTED_BANK ("CITRUSNB"),
	DIRECPAY_NETBANKING_SUPPORTED_BANK ("DIRECPAYNB"),
	//TMB NB added by vijay
	TMB_NB_PROCESSOR			("TMBNBProcessor"),
	TMB_NB("TMB_NB"),
	SHIVALIK_NB_PROCESSOR			("TransactionWSSHIVALIKNBBANKProcessor"),
	TFP_PROCESSOR			("TFPProcessor"),
	SHIVALIK_NB("SHIVALIK_NB"),
	//Recurring payments
	DAILY_CRON_STRING           	("DailyCronString"),
	RECURRING_PAYMENT_JOB			("recurringPaymentJob"),
	RECURRING_PAYMENT_JOB_TRIGGER  	("recurringPaymentJobTrigger"),
	CITRUSPAY						("citruspay"),
	CITRUSPAY_TRIGGER	         	("citruspayTrigger"),

	// CRM web service
	CRM_SERVICE_LOG_USER_PREFIX ("Log in from CRM web service: PayId"),
	CRM_APP_SALT_FILE_PATH_NAME ("CrmAppSaltFile"),
	SUBTRACTION_SIGN            ("-"),
	//help ticket
	HELPTICKET					("HelpTicket"),
	CONTANT_OK					("OK"),
	//YesUpi Enquiry Flag
	ENQUIRY_FLAG               ("YesBankAllowStatusEnquiry"),
	INVALID_VPA_MSG            ("Invalid VPA address"),
	ALLOWED_STATUS_ENQUIRY_COUNT   ("allowedStatusEnquiryCount"),
	STATUS_ENQUIRY_TYPE_LIST    ("statusEnquiryTypeList"),
	//Mongo db 
	DB_NAME						("dbName"),
	COLLECTION_NAME				("collectionName"),
	SETTLEMENT_COLLECTION_NAME	("settlementCollectionName"),
	REPORTING_COLLECTION_NAME	("reportingCollectionName"),
	SETTLED_TRANSACTIONS_NAME	("settledTransactionsName"),
	SUMMARY_TRANSACTIONS_NAME	("summaryTransactionsName"),
	DUPLICATE_SETTLEMENT_NAME	("duplicateSettlementName"),
	STATUS_ENQUIRY_COLLECTION_NAME	("statusEnquiryCollectionName"),
	STATUS_ENQUIRY_HISTORY_NAME	("statusEnquiryHistoryCollectionName"),
	DASHBOARD_POPULATOR_NAME	("dashboardPopulatorCollectionName"),
	CARDSAVE_TOKEN_NAME			("cardSaveTokenCollectionName"),
	BIN_DB_NAME					("binDbCollectionName"),
	INVOICE_COLLECTION_NAME		("invoiceCollectionName"),
	TRANSACTION_STATUS_COLLECTION		("transactionStatus"),
	TRANSACTION_STATUS_EXCEP_COLLECTION		("transactionStatusException"),
	TRANSACTION_STATISTICS_COLLECTION		("transactionStatistics"),
	HOST						("host"),
	PORT						("port"),
	MONGO_URI_PREFIX			("mongoURIprefix"),
	MONGO_URI_SUFFIX			("mongoURIsuffix"),
	MONGO_USERNAME				("username"),
	MONGO_PASSWORD				("password"),
	MONGO_URI					("mongoURI"),
	ENC_DATA                     ("encdata"),
	FRAUD_PREVENTION_COLLECTION_NAME ("fraudPreventionCollectionName"),
	// used for fraud report
	FRAUD_TRANSACTION_COLLECTION_NAME ("MONGO_DB_fraudTransactions"),

	BENEFICIARY_ACCOUNTS_COLLECTION_NAME			("beneficiaryAccountsCollectionName"),
	//fraud prevention module
	PG_FRAUD_TYPE				("FRAUD_TYPE"),
	PG_BLOCK_TYPE				("BLOCK_TYPE"),

	//
	PG_ACQUIRER_ERROR			("Response not received from acquirer"),

	// email Builder
	EMAIL_VALIDATORURL                    ("EmailValidatorUrl"),
	EMAIL_MERCHANT_VALIDATOR_URL                    ("EmailMerchantValidatorUrl"),
	EMAIL_MERCHANT_SIGNUP_NOTIFIER        ("EmailMerchantSignUpNotifier"),
	EMAIL_TRANSACTION_AUTHENTICATION      ("EmailTransactionAuthenticationUrl"),
	PG_DEMO_EMAIL                         ("noreply@pay10.com"),
	RESET_PASSWORD_URL                    ("ResetPasswordUrl"),
	RESET_MERCHANT_PASSWORD_URL                    ("ResetMerchantPasswordUrl"),
	CREATE_PASSWORD_URL                    ("CreatePasswordUrl"),
	CREATE_MERCHANT_PASSWORD_URL                    ("CreateMerchantPasswordUrl"),
	PAYMENT_RECEIVED_ACKNOWLEDGEMENT      (": Payment Received Acknowledgement"),
	REFUND_FOR_ODER_ID                    (": Refunded for Order Id :-"),
	ACCOUNT_VALIDATION_EMAIL              ("Account Validation Email - "),
	MERCHANT_SIGNUP_NOTIFICATION          ("Merchant Sign Up Notification -"),
	CRM_PASSWORD_CHANGE_ACKNOWLEDGEMENT   (": CRM password change Acknowledgement"),
	PAYMENT_ATHENTICATION_ACKNOWLEDGEMENT (": Payment Authentication Acknowledgement -"),
	REMITTANCE_PROCESSED                  (": Remittance Processed for :-"),
	RESET_PASSWORD_EMAIL                  ("Reset Password Email - "),
	INVOICE_LINK                          ( "Invoice Link"),
	SUCCESS_CODE                          ( "000"),
	SUCCESS                          ( "Success"),
	FAIL                          ( "Fail"),

	SEND_EMAIL_ON_SIGNUP					("sendEmailOnSignup"),
	SEND_EMAIL_ON_SIGNUP_LIST			  ("sendEmailOnSignupList"),

	// email service provider
	ACCOUNT_VALIDATE_ID                   ( "accountValidationID"),
	EMAIL                                 ( "email"),
	EMAILID                               ( "emailId"),
	NAME                                  ( "name"),
	URL                                   ( "url"),
	UTR                                   ( "utr"),
	MERCHANT_HOSTED_ENCRYPTION_KEY 		   ("merchantHostedEncryptionKey"),

	MERCHANT_TRANSACTION_DETAILS			("Merchant Transaction Details - "),
	REQUEST_URL							   ("requestUrl"),
	SALT("salt"),
	PAYID                                 ( "payId"),
	MERCHANT                              ( "merchant"),
	DATE_FROM                             ( "datefrom"),
	NET_AMOUNT                            ( "netAmount"),
	REMITTED_DATE                         ( "remittedDate"),
	REMITTED_AMOUNT                       ( "remittedAmount"),
	STATUS                                ( "status"),
	SUBJECT                               ( "subject"),
	MESSAGE_BODY                          ( "messageBody"),
	MESSAGE                               ( "message"),
	NOTIFICATION_EMAIL_ID                 ( "notifierEmailId"),
	VIEW_DATE                             ( "viewDate"),
	CONCERNED_USER                        ( "concernedUser"),
	SUBMITED_BY                           ( "submittedBy"),
	ACCOUNT_VALIDATION_KEY                ( "accountValidationKey"),
	UTF_8                                 ( "UTF-8"),
	CONTENT_TYPE                          ( "content-type"),
	APPLICATION_JSON                      ( "application/json"),
	EMAIL_ADD_USER                         ( "emailAddUser"),
	PASSWORD_CHANGE                         ( "passwordChange"),
	PASSWORD_RESET                         ( "passwordReset"),
	INVOICE_LINK_URL                       ( "invoiceLink"),
	REMITTANCE_PROCESS                     ( "remittanceProcess"),
	SEND_BULK_EMAIL_SERVICETAX             ( "sendBulkEmailServiceTax"),
	EMAIL_SEPARATOR		                   ("&"),
	EMAILVALIDATOR                         ( "emailValidator"),
	BUSINESS_NAME                          ( "businessName"),
	INVOICE_NO                             ( "invoiceNo"),
	CITY                                   ( "city"),
	COUNTRY                                ( "country"),
	STATE                                  ( "state"),
	ZIP                                    ( "zip"),
	PHONE                                  ( "phone"),
	ADDRESS                                ( "address"),
	PRODUCT_NAME                           ( "productName"),
	PRODUCT_DESC                           ( "productDesc"),
	QUANTITY                               ( "quantity"),
	INVOICE_AMOUNT                         ( "amount"),
	TOTAL_AMOUNT                           ( "totalAmount"),
	SERVICE_CHARGE                         ( "serviceCharge"),
	INVOICE_CURRENCY_CODE                  ( "currencyCode"),
	EXPIRES_DAY                            ( "expiresDay"),
	EXPIRES_HOUR                           ( "expiresHour"),
	CREATE_DATE                            ( "createDate"),
	UPDATE_DATE                            ( "updateDate"),
	SALT_KEY                               ( "saltKey"),
	RETURN_URL                             ( "returnUrl"),
	RECIPIENT_MOBILE                       ( "recipientMobile"),
	SHORT_URL                             ( "shortUrl"),
	INVOICE_TYPE                          ( "invoiceType"),
	SEND_PROMOSMS                         ( "sendPromoSMS"),
	UPDATE_REQUESTU_URL                   ( "updateRequestNotificationUrl"),
	UPDATE_APPROVED_REJECT_URL            ( "updateApproveRejectNotificationUrl"),
	BIN									  ( "bin"),
	INVOICEID                             ( "invoiceId"),
	ORDER_ID							  ("orderId"),
	PG_REF_NUM 							  ("pgRefNum"),
	RESPONSE_DATE_TIME					  ("ResponseDateTime"),
	INVOICE_OBJ							  ("invoiceObj"),

	// Email Sender Creds

	MAIL_SENDER                             ( "MailSender"),
	MAIL_USERNAME                           ( "MailUserName"),
	MAIL_PASSWORD                           ( "MailPassword"),
	//ADDED BY ABHISHEK  FOR EMAIL

	MAIL_HOST                                ("Mail_Host"),
	SOCKETFACTORY_PORT                      ("socketFactory_port"),
	SOCKETFACTORY_CLASS                     ("socketFactory_class"),
	MAIL_AUTH                                ("mail_auth"),
	MAIL_PORT                                 ("mail_port"),
	MAIL_PROTOCAL                              ("mail_protocal"),
	MAIL_STARTTLS                              ("mail_starttls"),
	TXN_WS_INTERNAL_VPA_VALIDATE						("TransactionWSInternalVPAVALIDATE"),

	//pg-ws
	TXN_WS_INTERNAL							("TransactionWSInternal"),
	TXN_MIGS_PROCESSOR						("TransactionWSMigsProcessor"),
	TXN_WS_IPAY_RETURN_URL					("TransactionWSIPayReturnUrl"),
	TXN_WS_FEDERAL_RETURN_URL				("TransactionWSFederalReturnUrl"),
	TXN_WS_UPI_PROCESSOR					("TransactionWSUPITransactUrl"),
	TXN_WS_BOB_PROCESSOR					("TransactionWSBobProcessor"),
	TXN_WS_KOTAK_PROCESSOR					("TransactionWSKotakProcessor"),
	TXN_WS_ATL_PROCESSOR					("TransactionWSAtlProcessor"),
	TXN_WS_RUPAY_PROCESSOR					("TransactionWSRupayProcessor"),
	TXN_WS_GOOGLEPAY_PROCESSOR				("TransactionWSGooglePayProcessor"),
	TXN_WS_IDBI_PROCESSOR				    ("TransactionWSIdbiProcessor"),
	TXN_WS_MATCHMOVE_PROCESSOR				("TransactionWSMatchMoveProcessor"),
	TXN_WS_DIRECPAY_PROCESSOR				("TransactionWSDirecpayProcessor"),
	TXN_WS_ISGPAY_PROCESSOR					("TransactionWSIsgpayProcessor"),
	TXN_WS_FSS_PROCESSOR					("TransactionWSFssProcessor"),
	TXN_WS_AXISBANK_NB_PROCESSOR			("TransactionWSAxisBankNBProcessor"),
	TXN_WS_AXISBANK_UPI_PROCESSOR			("TransactionWSAxisBankUPIProcessor"),
	TXN_WS_ATOM_PROCESSOR					("TransactionWSAtomProcessor"),
	TXN_WS_APBL_PROCESSOR					("TransactionWSApblProcessor"),
	TXN_WS_MOBIKWIK_PROCESSOR				("TransactionWSMobikwikProcessor"),
	TXN_WS_INGENICO_PROCESSOR				("TransactionWSIngenicoProcessor"),
	TXN_WS_PAYTM_PROCESSOR					("TransactionWSPaytmProcessor"),
	TXN_WS_PAYU_PROCESSOR					("TransactionWSPayuProcessor"),
	TXN_WS_PHONEPE_PROCESSOR				("TransactionWSPhonepeProcessor"),
	TXN_WS_LYRA_PROCESSOR					("TransactionWSLyraProcessor"),
	TXN_WS_LYRA_NB_PROCESSOR				("TransactionWSLyraNBProcessor"),
	TXN_WS_FREECHARGE_PROCESSOR				("TransactionWSFreeChargeProcessor"),
	TXN_WS_SBI_PROCESSOR					("TransactionWSSbiProcessor"),
	TXN_WS_ICICI_NB_PROCESSOR				("TransactionWSICICINBProcessor"),
	TXN_WS_CASHFREE_PROCESSOR				("TransactionWSCashfreeProcessor"),
	TXN_WS_EASEBUZZ_PROCESSOR				("TransactionWSEasebuzzProcessor"),
	TXN_WS_AGREEPAY_PROCESSOR				("TransactionWSAgreepayProcessor"),
	TXN_WS_FEDERALBANKNB_PROCESSOR			("TransactionWSFederalBankNBProcessor"),
	TXN_WS_YESBANKNB_PROCESSOR				("TransactionWSYesbankNBProcessor"),
	TXN_WS_PINELABS_PROCESSOR				("TransactionWSPinelabsProcessor"),
	TXN_WS_InterNalRefund					("RefundURL"),
	TXN_WS_CAMSPAY_PROCESSOR				("TransactionWSPCamsPayProcessor"),
	TXN_WS_DEMO_PROCESSOR				("TransactionWSDemoProcessor"),

	TXN_WS_QUOMO_PROCESSOR					("TransactionWSQuomoProcessor"),
	
	//Federal
	FEDERAL_ECI								("eci"),
	FEDERAL_CAVV							("cavv"),
	FEDERAL_MPI_ERROR_CODE					("mpiErrorCode"),
	FEDERAL_XID								("xid"),
	FEDERAL_AMOUNT							("purchase_amount"),
	FEDERAL_MERCHANT_HASH					("message_hash"),
	FEDERAL_MD								("md"),
	FEDERAL_CURRENCY						("currency"),
	FEDERAL_ID								("ID"),
	FEDERAL_STATUS							("status"),

	//Federal Upi
	FED_UPI_RESPONSE_CODE					("ResponseCode"),
	FED_UPI_RESPONSE						("Response"),
	FED_UPI_CUST_REFERENCE					("CustomerReference"),
	FED_UPI_APPROVAL_TIME					("ApprovalTime"),
	FED_UPI_PAYEE_APPROVAL_NUM				("PayeeApprovalNum"),
	FED_UPI_PAYER_APPROVAL_NUM				("PayerApprovalNum"),
	FED_UPI_SUCCESS_CODE					("00"),
	FED_UPI_RESP_VAL_ADD					("RespValAdd"),
	INDIA									("INDIA"),
	//Yes Upi
	YES_UPI_SUCCESS_CODE					("00"),
	YES_UPI_RESPONSE						("S"),
	YESBANK_UPI_MERCHANT_KEY                ("YesBank_Upi_Merchant_Key"),

	//Icici Upi
	ICICI_UPI_RESPONSE						("SUCCESS"),


	// IDFC Upi
	IDFC_UPI_SUCCESS_CODE					 ("000"),
	IDFC_UPI_RESPONSE_MSG					 ("Approved"),
	IDFC_UPI_DECODE_CHAR                     ("256"),

	FREECHARGE_UPI_SUCCESS_CODE				 ("SUCCESS"),

	//Axis Upi
	AXISBANK_UPI_SUCCESS_CODE				("00"),
	AXISBANK_UPI_RESPONSE					("SUCCESS"),
	AXISBANK_UPI_MERCHANT_KEY                ("YesBank_Upi_Merchant_Key"),

	OPERATION_NAME                           ("OperationName"),
	TXN_ID                                    ( "TxnId"),
	RESP_CODE                                 ("ResCode"),
	RESP_MSG                                  ("ResDesc"),
	IDFC_UPI_REQUEST_URL                     ( "IDFC_UPI_BANK_URL"),
	JKS_PASSWORD                             ("upi@321#"),
	JKS_FILE_NAME                       	("idfcupissl_preprd.jks"),
	PG_PROPERTIES_PATH                      ("STARPAY_PG_PROPS"),
	XML_RESPONSE                            ("<?xml"),
	HMAC                                       ("HMAC"),
	TIME_STAMP                                 ("TimeStamp"),
	DATEFORMAT                                ( "ddMMyyHHmmss"),
	KEK                                      ("KEK_IDFCUPI"),
	ENC_DEK                                  ("ENCRYPTED_DEK"),
	PAYEE_VIR_ADDR                           ("PayeeVirAddr"),
	ORG_TXN_REFID                            ("OrgTxnRefId"),
	PAYER_VIR_ADDR                           ("PayerVirAddr"),
	ORG_TXN_ID                               ("OrgTxnId"),
	ORG_CUST_REF_ID                          ("OrgCustRefId"),
	BANK_TXNID                               ("TxnId"),

	//KOTAK UPI
	KOTAK_UPI_SUCCESS_CODE					("00"),
	KOTAK_UPI_RESPONSE						("SUCCESS"),
	KOTAK_UPI_CHECKSUM_FAILURE_CODE			("009"),
	KOTAK_UPI_CHECKSUM_FAILURE_RESPONSE		("callBackCheckSumMismatch"),
	KOTAK_UPI_CHECKSUM                      ("checksum"),
	KOTAK_UPI_STATUS_CODE                   ("statusCode"),
	KOTAK_UPI_PAYEEVPA                      ("payeevpa"),
	KOTAK_UPI_STATUS                        ("status"),
	KOTAK_UPI_RRN                           ("rrn"),
	KOTAK_UPI_PAYERVPA                      ("payervpa"),
	KOTAK_UPI_TIMESTAMP                     ("transactionTimestamp"),
	KOTAK_UPI_REMARKS                       ("remarks"),
	KOTAK_UPI_ACQID                         ("transactionreferencenumber"),
	KOTAK_UPI_TRANSID                        ("transactionid"),
	//Hdfc Upi
	HDFC_UPI_SUCCESS_CODE					("00"),
	HDFC_UPI_ERROR_RESPONSE_CODE			("U19"),
	HDFC_UPI_INVALID_REQUEST_FIELD_CODE     ("002"),
	HDFC_UPI_CANCELLED_CODE                 ("003"),
	HDFC_UPI_INTERNAL_SYSTEM_ERROR_CODE     ("004"),
	HDFC_UPI_MERCHANT_KEY                    ("HdfcUpiMerchantKey"),
	//add surcharge flags
	FSS_ADD_SURCHARGE						("FSS_ADD_SURCHARGE"),
	YESBANKCB_ADD_SURCHARGE					("YESBANKCB_ADD_SURCHARGE"),
	YESBANKCB_UPI_ADD_SURCHARGE             ("YESBANKCB_UPI_ADD_SURCHARGE"),
	FIRSTDATA_ADD_SURCHARGE					("FIRSTDATA_ADD_SURCHARGE"),
	ICICI_ADD_SURCHARGE						("ICICI_ADD_SURCHARGE"),
	IDFCUPI_ADD_SURCHARGE                   ("IDFCUPI_ADD_SURCHARGE"),
	FEDERAL_ADD_SURCHARGE					("FEDERAL_ADD_SURCHARGE"),
	AXIS_MIGS_ADD_SURCHARGE					("AXIS_MIGS_ADD_SURCHARGE"),
	BOB_ADD_SURCHARGE						("BOB_ADD_SURCHARGE"),
	ATL_ADD_SURCHARGE						("ATL_ADD_SURCHARGE"),
	KOTAK_ADD_SURCHARGE						("KOTAK_ADD_SURCHARGE"),
	IDBIBANK_ADD_SURCHARGE					("IDBIBANK_ADD_SURCHARGE"),
	DIRECPAY_ADD_SURCHARGE					("DIRECPAY_ADD_SURCHARGE"),
	ISGPAY_ADD_SURCHARGE					("ISGPAY_ADD_SURCHARGE"),
	KOTAKUPI_ADD_SURCHARGE                  ("KOTAKUPI_ADD_SURCHARGE"),
	ICICI_MPGS_ADD_SURCHARGE                ("ICICI_MPGS_ADD_SURCHARGE"),
	MATCHMOVE_ADD_SURCHARGE                 ("MATCHMOVE_ADD_SURCHARGE"),
	HDFC_ADD_SURCHARGE						("HDFC_ADD_SURCHARGE"),
	BILLDESK_ADD_SURCHARGE					("BILLDESK_ADD_SURCHARGE"),
	LYRA_ADD_SURCHARGE						("LYRA_ADD_SURCHARGE"),
	SBI_ADD_SURCHARGE						("SBI_ADD_SURCHARGE"),
	FREECHARGE_ADD_SURCHARGE                ("FREECHARGE_ADD_SURCHARGE"),
	CASHFREE_ADD_SURCHARGE					("CASHFREE_ADD_SURCHARGE"),
	EASEBUZZ_ADD_SURCHARGE					("EASEBUZZ_ADD_SURCHARGE"),
	AGREEPAY_ADD_SURCHARGE					("AGREEPAY_ADD_SURCHARGE"),
	FEDERALNB_ADD_SURCHARGE					("FEDERALNB_ADD_SURCHARGE"),
	YESBANKNB_ADD_SURCHARGE					("YESBANKNB_ADD_SURCHARGE"),
	PINELABS_ADD_SURCHARGE					("PINELABS_ADD_SURCHARGE"),
	CAMSPAY_ADD_SURCHARGE					("CAMSPAY_ADD_SURCHARGE"),
	BOB_CARD_NUMBER							("card"),
	BOB_EXP_MONTH							("expmonth"),
	BOB_EXP_YEAR							("expyear"),
	BOB_CVV									("cvv2"),
	FED_CARD_NUMBER							("pan"),
	FED_EXP_MONTH_YEAR						("expiry"),
	FED_EXP_MONTH							("exp_date_mm"),
	FED_EXP_YEAR							("exp_date_yyyy"),
	FED_CVV									("cvv2"),
	MIGS_CARD_NUMBER						("vpc_CardNum"),
	MIGS_EXP								("vpc_CardExp"),
	MIGS_CVV								("vpc_CardSecurityCode"),
	FIRST_DATA_CARD							("CardNumber"),
	FIRST_DATA_EXP_MONTH					("ExpMonth"),
	FIRST_DATA_EXP_YEAR						("ExpYear"),
	FIRST_DATA_CVV							("CardCodeValue"),



	//For SMS Gateway
	AUTH_KEY                      ("AUTH_KEY"),
	SMS_URL                       ("SMS_URL"),
	SENDER_ID                     ("SENDER_ID"),
	SENDER_PASSWORD               ("SENDER_PASSWORD"),
	SENDER_NAME                   ("SENDER_NAME"),


	//For supported Payment Type
	RUPAY									("RUPAY"),
	VISA									("VISA"),
	MASTERCARD								("MASTERCARD"),
	AMEX									("AMEX"),
	MAESTRO									("MAESTRO"),
	DINERS									("DINERS"),
	PAYMENT_TYPE_UP							("UP="),
	PAYMENT_TYPE_NB							("NB="),
	PAYMENT_TYPE_DP							("DP="),
	PAYMENT_TYPE_DC							("DC="),
	PAYMENT_TYPE_PC							("PC="),
	PAYMENT_TYPE_QR							("QR="),
	PAYMENT_TYPE_EMI						("EMI="),
	PAYMENT_TYPE_CC							("CC="),
	PAYMENT_TYPE_AD							("AD="),
	PAYMENT_TYPE_WL							("WL="),
	NA										("NA"),
	MOP_COMMA								(","),
	TRUE_STRING								("true"),
	MOP_VISA								("VI"),
	MOP_MASTERCARD							("MC"),
	MOP_RUPAY								("RU"),
	MOP_MAESTRO								("MS"),
	MOP_AMEX								("AX"),
	MOP_DINNER								("DN"),
	MERCHANT_PAYMENT_AD						("AD"),
	MERCHANT_PAYMENT_CARD					("CARD"),
	COLLECT_AUTH							("COLLECT_AUTH"),
	MERCHANT_PAYMENT_UPI					("UPI"),
	MERCHANT_PAYMENT_WL						("PPI"),
	MERCHANT_PAYMENT_NB						("NB"),

	MOP_DISCOVER							("DI"),
	DISCOVER								("DISCOVER"),

	TXN_WS_PAYTEN_PROCESSOR 	("TransactionWSPAY10Processor"),

	// Wallets

	PAYTM									("PAYTM_WALLET"),
	MOBIKWIK								("MOBIKWIK_WALLET"),
	OLAMONEY								("OLAMONEY_WALLET"),
	MATCHMOVE								("MATCHMOVE_WALLET"),
	AMAZONPAY								("AMAZON_PAY_WALLET"),
	AIRTELPAY								("AIRTEL_PAY_WALLET"),
	FREECHARGE								("FREECHARGE_WALLET"),
	GOOGLEPAY								("GOOGLE_PAY_WALLET"),
	ITZCASH									("ITZ_CASH_WALLET"),
	JIOMONEY								("JIO_MONEY_WALLET"),
	MPESA									("M_PESA_WALLET"),
	OXYZEN									("OXYZEN_WALLET"),
	PHONEPE									("PHONE_PE_WALLET"),
	SBIBUDDY								("SBI_BUDDY_WALLET"),
	ZIPCASH									("ZIP_CASH_WALLET"),
	
	GCASH								    ("GCASH_WALLET"),
	MAYA									("MAYA_WALLET"),

	//Settlement API
	BENEFICIARY_CODE						("beneficiaryCode"),
	VERSION									("version"),
	UNIQUE_REQUEST_NO						("uniqueRequestNo"),
	APP_ID									("appID"),
	PURPOSE_CODE							("purposeCode"),
	CUSTOMER_ID								("customerID"),
	DEBIT_ACCOUNT_NO						("debitAccountNo"),
	BENEFICIARY								("beneficiary"),
	TRANSFER_TYPE							("transferType"),
	TRANSFER_CURRENCY_CODE					("transferCurrencyCode"),
	TRANSFER_AMOUNT							("transferAmount"),
	REMITTER_INFO							("remitterToBeneficiaryInfo"),
	START_TRANSFER							("startTransfer"),

	SWITCH_ACQUIRER_AMOUNT 					("SWITCH_ACQUIRER_AMOUNT"),
	MOP_GOOGLEPAY							("GP"),
	MOP_GOOGLEPAY_PARAMETER					("GOOGLEPAY"),
	PAYMENT_RECV							("PAYMENT_RECV"),
	USE_STATIC_DATA							("useStaticData"),
	USE_DATE_INDEX							("useDateIndex"),
	USE_PG_DATE_TIME_INDEX					("usePGDateTimeIndex"),
	USE_CAPTURED_DATE_INDEX					("useCapturedDateIndex"),


	//For Netbanking dropDown list

	AXISBANK                              ("Axis Bank"),
	BANK_OFBAHRAIN_AND_KUWAIT             ("Bank Of Bahrain And Kuwait"),
	B_OI                                 ("Bank Of India"),
	BANK_OFMAHARASHTRA 				   ("Bank Of Maharashtra"),
	CANARABANK 				           ("Canara Bank"),
	CENTRAL_BANK_OFINDIA 				   ("Central Bank Of India"),
	CITI_BANK 							   ("CitiBank"),
	CITY_UNIONBANK 					   ("City Union Bank"),
	CORPORATIONBANK 					   ("Coporation Bank"),
	DEUTSCHEBANK						   ("Deutsche Bank"),
	DEVELOPMENT_CREDITBANK 			   ("Development Credit Bank"),
	FEDERALBANK						   ("Federal Bank"),
	HDFCBANK 							   ("HDFC Bank"),
	ICICIBANK							   ("ICICI Bank"),
	INDIANBANK						       ("Indian Bank"),
	YESBANKCB 							   ("YES BANK CB"),
	INDIANOVERSEAS_BANK				   ("Indian Overseas Bank"),
	INDUSINDBANK 						   ("Indusind Bank"),
	INDUSTRIAL_DEVELOPMENTBANK_OF_INDIA   ("Industrial Development Bank Of India"),
	ING_VYSYABANK 						   ("IngVysya Bank"),
	JAMMU_AND_KASHMIRBANK                 ("Jammu And Kashmir Bank"),
	KARNATAKA_BANKLTD                     ("Karnatka Bank Ltd"),
	KARUR_VYSYABANK                       ("KarurVysya Bank"),
	KOTAKBANK                             ("Kotak Bank"),
	ORIENTAL_BANK_OFCOMMERCE              ("Oriental Bank Of Commerce"),
	RATNAKARBANK                          ("Ratnakar Bank"),
	SOUTH_INDIANBANK                      ("South Indian Bank"),
	STATE_BANK_OFBIKANER_AND_JAIPUR       ("State Bank Of Bikaner And Jaipur"),
	STATE_BANK_OFHYDERABAD                ("StateBank Of Hyderabad"),
	STATE_BANK_OFINDIA                    ("State Bank Of India"),
	STATE_BANK_OFMYSORE                   ("State Bank Of Mysore"),
	STATE_BANK_OFPATIALA                  ("State Bank Of Patiala"),
	STATE_BANK_OFTRAVANCORE               ("State Bank Of Travancore"),
	TAMILNAD_MERCANTILEBANK               ("Tamilnad Mercantile Bank"),
	UNION_BANK_OFINDIA                    ("Union Bank Of India"),
	UNITED_BANK_OFINDIA                   ("United Bank Of India"),
	VIJAYABANK                            ("Vijaya Bank"),
	YESBANK                               ("Yes Bank"),
	IDFCUPIBANK                           ("IdfcUpi Bank"),
	ANDHRABANK                            ("Andhra Bank"),
	BANK_OF_BARODACORPORATE_ACCOUNTS      ("Bank of Baroda Corporate Accounts"),
	BANK_OF_BARODARETAIL_ACCOUNTS         ("Bank of Baroda Retail Accounts"),
	CATHOLIC_SYRIANBANK                   ("Catholic Syrian Bank"),
	LAKSHMI_VILAS_BANKNETBANKING          ("Lakshmi Vilas Bank NetBanking"),
	PUNJAB_NATIONALBANK                   ("Punjab National Bank"),
	STANDARD_CHARTEREDBANK                ("Standard Chartered Bank"),
	SYNDICATEBANK                         ("Syndicate Bank"),
	AXIS_CORPORATEBANK                    ("Axis Corporate Bank"),
	ICICI_CORPORATEBANK                   ("ICICI Corporate Bank"),
	PNB_CORPORATEBANK                     ("PNB Corporate Bank"),
	HSBCBANK                              ("HSBC Bank"),
	UCOBANK                               ("UCO Bank"),
	COSMOSBANK                            ("COSMOS Bank"),
	ALLAHABADBANK                         ("Allahabad Bank"),
	BANK_OFBARODA                         ("Bank of Baroda"),
	DHANLAXMIBANK                         ("Dhanlaxmi_Bank"),
	PUNJAB_AND_SINDBANK                   ("Punjab And Sind Bank"),
	RBL_NETBANK                           ("RBL Bank"),
	IDBI_NETBANK                          ("IDBI Bank"),

	// Direcpay Only
	DEMO_BANK 							   ("Demo Bank"),
	AXIS_BANK                              ("Axis Bank"),
	BANK_OF_BAHRAIN_AND_KUWAIT             ("BANK_OF_BAHRAIN_AND_KUWAIT"),
	BOI                                    ("BOI"),
	BANK_OF_MAHARASHTRA 				   ("BANK_OF_MAHARASHTRA"),
	CANARA_BANK 				           ("CANARA_BANK"),
	CENTRAL_BANK_OF_INDIA 				   ("CENTRAL_BANK_OF_INDIA"),
	CITIBANK 							   ("CITIBANK"),
	CITY_UNION_BANK 					   ("CITY_UNION_BANK"),
	CORPORATION_BANK 					   ("CORPORATION_BANK"),
	DEUTSCHE_BANK						   ("DEUTSCHE_BANK"),
	DEVELOPMENT_CREDIT_BANK 			   ("DEVELOPMENT_CREDIT_BANK"),
	FEDERAL_BANK						   ("FEDERAL_BANK"),
	HDFC_BANK 							   ("HDFC_BANK"),
	ICICI_BANK							   ("ICICI_BANK"),
	INDIAN_BANK						       ("INDIAN_BANK"),
	YESBANK_CB 							   ("YESBANK_CB"),
	INDIAN_OVERSEAS_BANK				   ("INDIAN_OVERSEAS_BANK"),
	INDUSIND_BANK 						   ("INDUSIND_BANK"),
	INDUSTRIAL_DEVELOPMENT_BANK_OF_INDIA   ("INDUSTRIAL_DEVELOPMENT_BANK_OF_INDIA"),
	ING_VYSYA_BANK 						   ("ING_VYSYA_BANK"),
	JAMMU_AND_KASHMIR_BANK                 ("JAMMU_AND_KASHMIR_BANK"),
	KARNATAKA_BANK_LTD                     ("KARNATAKA_BANK_LTD"),
	KARUR_VYSYA_BANK                       ("KARUR_VYSYA_BANK"),
	KOTAK_BANK                             ("KOTAK_BANK"),
	ORIENTAL_BANK_OF_COMMERCE              ("ORIENTAL_BANK_OF_COMMERCE"),
	RATNAKAR_BANK                          ("RATNAKAR_BANK"),
	SOUTH_INDIAN_BANK                      ("SOUTH_INDIAN_BANK "),
	STATE_BANK_OF_BIKANER_AND_JAIPUR       ("STATE_BANK_OF_BIKANER_AND_JAIPUR"),
	STATE_BANK_OF_HYDERABAD                ("STATE_BANK_OF_HYDERABAD"),
	STATE_BANK_OF_INDIA                    ("STATE_BANK_OF_INDIA"),
	STATE_BANK_OF_MYSORE                   ("STATE_BANK_OF_MYSORE"),
	STATE_BANK_OF_PATIALA                  ("STATE_BANK_OF_PATIALA"),
	STATE_BANK_OF_TRAVANCORE               ("STATE_BANK_OF_TRAVANCORE"),
	TAMILNAD_MERCANTILE_BANK               ("TAMILNAD_MERCANTILE_BANK "),
	UNION_BANK_OF_INDIA                    ("UNION_BANK_OF_INDIA"),
	UNITED_BANK_OF_INDIA                   ("UNITED_BANK_OF_INDIA"),
	VIJAYA_BANK                            ("VIJAYA_BANK"),
	YES_BANK                               ("YES_BANK"),
	IDFCUPI_BANK                           ("IDFCUPI_BANK"),
	ANDHRA_BANK                            ("ANDHRA_BANK"),
	BANK_OF_BARODA_CORPORATE_ACCOUNTS      ("BANK_OF_BARODA_CORPORATE_ACCOUNTS"),
	BANK_OF_BARODA_RETAIL_ACCOUNTS         ("BANK_OF_BARODA_RETAIL_ACCOUNTS"),
	CATHOLIC_SYRIAN_BANK                   ("CATHOLIC_SYRIAN_BANK"),
	LAKSHMI_VILAS_BANK_NETBANKING          ("LAKSHMI_VILAS_BANK_NETBANKING"),
	PUNJAB_NATIONAL_BANK                   ("PUNJAB_NATIONAL_BANK"),
	STANDARD_CHARTERED_BANK                ("STANDARD_CHARTERED_BANK"),
	SYNDICATE_BANK                         ("SYNDICATE_BANK"),
	AXIS_CORPORATE_BANK                    ("AXIS_CORPORATE_BANK"),
	ICICI_CORPORATE_BANK                   ("ICICI_CORPORATE_BANK"),
	PNB_CORPORATE_BANK                     ("PNB_CORPORATE_BANK"),
	HSBC_BANK                              ("HSBC_BANK"),
	UCO_BANK                               ("UCO_BANK"),
	COSMOS_BANK                            ("COSMOS_BANK"),
	ALLAHABAD_BANK                         ("ALLAHABAD_BANK"),
	BANK_OF_BARODA                         ("BANK_OF_BARODA"),
	DHANLAXMI_BANK                         ("DHANLAXMI_BANK"),
	PUNJAB_AND_SIND_BANK                   ("PUNJAB_AND_SIND_BANK"),
	RBL_NET_BANK                           ("RBL_NET_BANK"),
	IDBI_NET_BANK                          ("IDBI_NET_BANK"),
	//PrepareRequestParemeter
	PAYMENT_ADSIMG_URL              ("Payment_AdsImgUrl"),
	PAYMENT_ADSIMG_LINK_URL         ("Payment_AdsImglinkUrl"),
	ADS                             ("ads"),
	CHARGEBACK_DOC_UPLOAD_PATH		("chargeback_docUploadPath"),
	CHARGEBACK_DOC_UPLOAD_EXTENSION ("chargeback_docUploadExtension"),

	MERCHANT_ONBOARD_DOC_UPLOAD_PATH		("merchant_onBoard_docUploadPath"),
	MERCHANT_ONBOARD_DOC_UPLOAD_EXTENSION 		("merchant_onBoard_docUploadExtension"),

	MONTHLY_INVOICE_DESTINATION_PATH        ("monthly_inVoice_destinationPath"),
	DEFAULT_COMPANY_TENANTID        		("DEFAULT_COMPANY_TENANTID"),
	COMPANY_LOGO_LOCATION        			("COMPANY_LOGO_LOCATION"),

	TENANT_DOC_UPLOAD_PATH					("Tenant_docUploadPath"),
	TENANT_DOC_UPLOAD_EXTENSION 			("Tenant_docUploadExtension"),
	TENANT_PGLOGO_UPLOAD_EXTENSION 			("Tenant_PgLogoUploadExtension"),

	//Schedular
	RESPONSE_MESSAGE_TEXT 					("responseMessage"),

	//Reco
	INPUT_FILE_NAME             			("input.file.name"),
	FORWARD_SLASH_SEPERATOR     			("\\"),
	OUTPUT_DATE_FORMAT_DB       			("yyyy-MM-dd HH:mm:ss"),
	INPUT_DATE_FORMAT_DB        			("yyyyMMddhhmmss"),
	REFUND_RECO_DATE_FORMAT_DB      		("yyyyMMdd"),
	RECO_TRUE                               ("TRUE"),
	RECO_FALSE                              ("FALSE"),
	IS_DEBUG                                ("IsDebug"),
	RECO_SUCCESS                            ("SUCCESS"),
	DATE_TIME_STAMP                 		("dateTimeStamp"),
	RECO_MERCHANT                   	 	("Merchant"),
	BANK                        			("Bank"),
	HASHING_ALGORITHAM                  	("SHA-256"),
	EXT_ACQ_PREFIX              			("Ext_Acq_"),
	/*SETTLE_DATE_FORMAT_DB       			("dd/MM/yyyy"),
    UPI_SETTLE_DATE_FORMAT_DB       		("dd/MM/yyyy"),*/
	R_FLAG                      			("R"),
	C_FLAG                      			("C"),
	EXCEPTION_STATUS            			("PENDING"),
	//ACQUIRER NAME IN MPR FILE
	IDBI_BANK_CDC               			("IDBI_CDC"),
	YES_BANK_CDC                			("YEBANK_CDC"),
	BOB_BANK_CDC                			("BOB_CDC"),
	KOTAK_BANK_CDC              			("KOTAKBANK_CDC"),
	ISGPAY_CDC                      		("ISGPAY_CDC"),
	DIRECPAY_CDC                			("DIRECPAY_CDC"),
	FSS_CDC                                 ("FSS_CDC"),
	YES_BANK_UPI                			("YES_UPI"),
	FEDERAL_BANK_CDC            			("FEDERAL_CDC"),
	ATOM_CDC                        		("ATOM_CDC"),
	QUOMO_CDC                        		("QUOMO_CDC"),
	QUOMO_NB                        		("QUOMO_NB"),
	AXISBANK_CDC                            ("AXISBANK_CDC"),
	AXISBANK_UPI                    		("AXISBANK_UPI"),
	APBL_CDC								("APBL_CDC"),
	APBL_UPI								("APBL_UPI"),
	APBL_WL									("APBL_WL"),
	PAYTM_WL				  				("PAYTM_WL"),
	PAYTM_CDC				  				("PAYTM_CDC"),
	MOBIKWIK_WL								("MOBIKWIK_WL"),
	MOBIKWIK_CDC							("MOBIKWIK_CDC"),
	INGENICO_CDC							("INGENICO_CDC"),
	PHONEPE_WL								("PHONEPE_WL"),
	PHONEPE_CDC								("PHONEPE_CDC"),
	PAYU_CDC								("PAYU_CDC"),
	BILLDESK_CDC							("BILLDESK_CDC"),
	HDFC_CDC                            	("HDFC_CDC"),
	CASHFREE_CDC                            ("CASHFREE_CDC"),
	CASHFREE_NB                             ("CASHFREE_NB"),
	CASHFREE_UPI                            ("CASHFREE_UPI"),
	CASHFREE_WL                             ("CASHFREE_WL"),
	EASEBUZZ_CDC                            ("EASEBUZZ_CDC"),
	EASEBUZZ_NB                             ("EASEBUZZ_NB"),
	EASEBUZZ_UPI                            ("EASEBUZZ_UPI"),
	EASEBUZZ_WL                             ("EASEBUZZ_WL"),

	//added by sonu for SBI MPR File upload
	SBI_CDC                                 ("SBI_CDC"),
	SBI_NB                                  ("SBI_NB"),

	AGREEPAY_CDC                            ("AGREEPAY_CDC"),
	AGREEPAY_NB                             ("AGREEPAY_NB"),
	AGREEPAY_UPI                            ("AGREEPAY_UPI"),
	AGREEPAY_WL                             ("AGREEPAY_WL"),
	YESBANKCB_CDC							("YESBANKCB_CDC"),
	YESBANKCB_UPI							("YESBANKCB_UPI"),
	UPTIME_TOKEN							("UPTIME_TOKEN"),
	UPTIME_USER_PAYID						("UPTIME_USER_PAYID"),
	YES_BANK_NODAL_FT3_BENE_MAINTENANCE		("YesBankNodalFT3BeneMaintenance"),
	YES_BANK_NODAL_FT3_DOMESTIC_PAYMENT		("YesBankNodalFT3FundTransfer"),
	YES_BANK_NODAL_FT3_PAYMENT_DETAILS		("YesBankNodalFT3PaymentDetails"),
	YES_BANK_NODAL_FT3_FUND_CONFIRMATION	("YesBankNodalFT3FundConfirmation"),
	ASIANCHECKOUT_PFX_PATH						("AsianCheckoutPfxPath"),
	ASIANCHECKOUT_PASSPHRASE					("AsianCheckoutPassPhrase"),
	YES_BANK_NODAL_FT3_BASIC_AUTH_BENE_USERNAME		("YesBankFT3BasicAuthBeneMaintenanceUsername"),
	YES_BANK_NODAL_FT3_BASIC_AUTH_BENE_PASSWORD		("YesBankFT3BasicAuthBeneMaintenancePassword"),
	YES_BANK_NODAL_FT3_BASIC_AUTH_USERNAME			("YesBankFT3BasicAuthUsername"),
	YES_BANK_NODAL_FT3_BASIC_AUTH_PASSWORD			("YesBankFT3BasicAuthPassword"),
	YES_BANK_NODAL_FT3_CLIENT_ID			("YesBankFT3ClientId"),
	YES_BANK_NODAL_FT3_CLIENT_SECRET		("YesBankFT3ClientSecret"),
	BENEFICIARY_CSV_RECORD_LIMIT			("BeneficiaryCsvRecordLimit"),
	BENEFICIARY_CSV_FILE_SIZE					("BeneficiaryCsvFileSize"),
	HASHING_ALGORITHAM_512                  ("SHA-512"),
	AUTH_FAIL                         		( "Authorization Fail"),
	GET_OTP_ID_TILE_API_TOKEN				("GET_OTP_ID_TILE_API_TOKEN"),
	PGWS_UPTIME_URL							("PGWS_UPTIME_URL"),
	BATCH_ID								("BATCH_ID"),
	TXN_WS_BILLDESK_PROCESSOR				("TransactionWSBilldeskProcessor"),
	DOMESTIC_PAYMENTS_REGION				("DOMESTIC"),
	INTERNAL_API_TOKEN						("INTERNAL_API_TOKEN"),
	WEBHOOK_SAVE_EVENT						("Webhook_Save_Event"),
	WEBHOOK_EVENT_BY_ASSOCIATION_ID			("Webhook_Event_By_AssociationId"),
	WEBHOOK_SAVED_DETAILS                   ("Webhook_Get_SaveDetails"),

	DIFF_HIGHLIGHT_API					 	("DIFF_HIGHLIGHT_API"),
	DIFF_PDF_API							("DIFF_PDF_API"),

	SBICARD_CDC                         ("SBICARD_CDC"),
	TFP_CDC                         ("TFP_CDC"),

	SBINB_NB                            ("SBINB_NB"),
	SBINB_CDC                            ("SBINB_CDC"),
	FEDERAL_NB							("FEDERAL_NB"),
	FEDERAL_CDC							("FEDERAL_CDC"),
	FEDERAL_UPI							("FEDERAL_UPI"),
	FEDERAL_WL						    ("FEDERAL_WL"),
	PINELABS_NB						    ("PINELABS_NB"),
	PINELABS_CDC                        ("PINELABS_CDC"),
	PINELABS_UPI                        ("PINELABS_UPI"),
	PINELABS_WL                         ("PINELABS_WL"),
	YESBANKNB_NB						("YESBANKNB_NB"),
	YESBANKNB_CDC						("YESBANKNB_CDC"),
	AXISBANK_NB							("AXISBANK_NB"),
	AXISBANK_WL							("AXISBANK_WL"),
	PAYU_NB								("PAYU_NB"),
	PAYU_UPI                            ("PAYU_UPI"),
	PAYU_WL								("PAYU_WL"),
	ATOM_NB								("ATOM_NB"),
	ATOM_UPI                            ("ATOM_UPI"),
	ATOM_WL								("ATOM_WL"),
	AXIS_BANKS_CDC						("AXIS BANK_CDC"),
	NBFEDERAL_NB						("NBFEDERAL_NB"),
	NBFEDERAL_CDC						("NBFEDERAL_CDC"),
	KOTAK_BANKS_CDC						("KOTAK Bank_CDC"),
	UPI_S2S_VPA_VALID					("VPA"),
	UPI_S2S_COLLECT_PAY					("COLLECTPAY"),
	RESELLER_COMMISSION_DEFAULT_ENTRY	("RESELLER_COMMISSION_DEFAULT_ENTRY"),
	CAMSPAY_CDC								("CAMSPAY_CDC"),
	CAMSPAY_NB								("CAMSPAY_NB"),
	CAMSPAY_UPI                            ("CAMSPAY_UPI"),
	SHIVALIKNMBANK_NB								("SHIVALIKNMBANK_NB"),
	CITYUNIONBANK_NB								("CITYUNIONBANK_NB"),

	TXN_WS_COSMOSUPI_PROCESSOR			("CosmosUPIResponseHandlerURL"),
	TXN_WS_COSMOSUPI_PROCESSOR_INTENT			("CosmosUPIResponseHandlerintentURL"),
	Liability_HOLD_AND_RELEASE		("libilityHoldAndRelease"),
	JAMMUANDKISHMIR_ADD_SURCHARGE			("JAMMUANDKISHMIR_ADD_SURCHARGE"),
	TXN_WS_IDFCBANK_NB_PROCESSOR  			("TransactionWSIdfcBankNBProcessor"),
	IDFC_ADD_SURCHARGE                   ("IDFC_ADD_SURCHARGE"),
	SHIVALIKNMBANK_ADD_SURCHARGE                   ("SHIVALIKNMBANK_ADD_SURCHARGE"),
	TFP_ADD_SURCHARGE                   ("TFP_ADD_SURCHARGE"),
	CANARANBBANK_ADD_SURCHARGE          ("CANARANBBANK_ADD_SURCHARGE"),
	TXN_WS_JAMMUANBKISHMIR_PROCESSOR		("TransactionWSJammuAndkishmirBankNBProcessor"),
	JAMMU_AND_KISHMIR_BANK						   ("Jammu and kishmir Bank"),
	JAMMUANDKASHMIR_NB                          ("JAMMUANDKASHMIR_NB"),
	JAMMUANDKASHMIR                          ("JAMMUANDKASHMIR"),
	COSMOS_UPI                           ("COSMOS"),
	IDFC_NB                          ("IDFC_NB"),
	CANARA_NB                   ("CANARA_NB"),TFP                ("TFP"),
	CANARA_NB_PROCESSOR			("CanaraNBProcessor"),
	CANARANBBANK_CDC                  ("CANARANBBANK_CDC"),
	//		COSMOS_ADD_SURCHARGE                  ("COSMOS_ADD_SURCHARGE"),
	CHARGEBACK_STATUS_UPDATE               ("CHARGEBACK_STATUS_UPDATE"),
	TXN_WS_KOTAK_CARD_PROCESSOR				("TransactionWSKotakCardProcessor"),

	LIABILITYMAILTO               ("LIABILITYMAILTO"),
	MAILTOFORCHARGEBACK               ("MAILTOFORCHARGEBACK"),
	EKYC_VERIFICATION          ("Ekyc Need to Reverify"),
	EKYC_DETAILS_NOT_FOUND("KYC Details Not Found"),
	EKYC_SERVICE_DOWN("Transaction not complete, Please Try Again Later"),

	DOWNLOAD_PATH("DOWNLOAD_PATH"),
	KOTAK_CARD_BANKS_CDC   ("KOTAK_CARD_CDC"),
	MERCHANT_HOSTED_S2S("S2S flag is not enabled"),
	COSMOS_ADD_SURCHARGE                  ("COSMOS_ADD_SURCHARGE"),
	BSESPAYID			("BSESPAYID"),
	BSESCONTROL			("BSESCONTROL"),
	BSESCOUNTERNO			("BSESCOUNTERNO"),
	BSESPAYMENT			("BSESPAYMENT"),
	BSESBILLINGCYCLE			("BSESBILLINGCYCLE"),
	BSESCOMPANYCODE			("BSESCOMPANYCODE"),
	BSESPAYMENTMODE			("BSESPAYMENTMODE"),
	BSESFILELOCATION 		("BSESFILELOCATION"),
	DEMO 		("DEMO"),
	PDF_FILES_BASE_PATH("PDF_FILES_BASE_PATH"),
	SBI_RUPAY_PA_RQ_FINAL_RESPONSE_HANDLER("SBI_RUPAY_PA_RQ_FINAL_RESPONSE_HANDLER"),

	PDF_MERGE_PATH("PDF_MERGE_PATH"),
	SBI_PA_RQ_FINAL_RESPONSE_HANDLER("SBI_PA_RQ_FINAL_RESPONSE_HANDLER"),
	TDR_NOT_SET_FOR_THIS_AMOUNT			("Tdr Not Set For This Amount"),
	GrievanceRedressalSystemDocUpload				("GrievanceRedressalSystemDocUpload"),
	GrievanceRedressalSystem				("GrievanceRedressalSystem"),
	GrievanceRedressalSystemHistory				("GrievanceRedressalSystemHistory"),
	GrievanceRedressalSystemDescriptionHistory				("GrievanceRedressalSystemDescriptionHistory"),
	OLDBHARTIPAY 		("OLDBHARTIPAY"),
	CITYUNIONBANK_ADD_SURCHARGE ("CITYUNIONBANK_ADD_SURCHARGE"),
	TXN_WS_HTPAY_PROCESSOR ("TXN_WS_HTPAY_PROCESSOR"),
	CARD_STAR         ("******"),
	COMMISSION_PO ("CommissionPO"),
	TRANSACTION_LEDGER_PO  ("PO_Transaction"),
	TRANSACTION_LEDGER_PO_TransactionStatus  ("PO_TransactionStatus"),
	TXN_WS_INTERNAL_PAYOUT							("TransactionWSInternalPayout"),
	PO_SETTELEMENT_COLLECTION ("PO_SETTELEMENT_COLLECTION"),
	PO_FRM ("PO_FRM"),
	CASH_DEPOSIT_PO  ("CashDepositPO"),
	WALLET_HISTORY("WalletHistory"),
	PASSBOOK_PO("PassbookPO"),
	PAYOUT_AUDIT_TRIAL("PayoutAuditTrail"),
	RESPONSE_CALLBACK_PAY_IN("ResponseCallbackPayIn"),
	RESPONSE_CALLBACK_PAY_OUT("ResponseCallbackPayOut"),
	RESPONSE_WEBHOOK_PAY_IN("ResponseWebhookPayIn"),
	RESPONSE_WEBHOOK_PAY_OUT("ResponseWebhookPayOut"),
	RESPONSE_STATUS_QUERY_PAY_IN("ResponseStatusQueryPayIn"),
	RESPONSE_STATUS_QUERY_PAY_OUT("ResponseStatusQueryPayOut"),
	PASSWORD_SET( "passwordSet"),
	SET_PASSWORD_EMAIL              ("Set Password Email - ");
	private final String value;

	private Constants(String value){
		this.value = value;
	}

	public String getValue() {
		return value;
	}



}

