// JavaScript Document
function show_block(val)
{
	if(val==1)
	{
	document.getElementById('imgm').style.display="block";
	document.getElementById('imgp').style.display="none";
	document.getElementById('bb1').style.display="block";
	}
	if(val==2)
	{
	document.getElementById('imgm1').style.display="block";
	document.getElementById('imgp1').style.display="none";
	document.getElementById('bb2').style.display="block";
	}
	if(val==3)
	{
	document.getElementById('imgm2').style.display="block";
	document.getElementById('imgp2').style.display="none";
	document.getElementById('bb3').style.display="block";
	}
	if(val==4)
	{
	document.getElementById('imgm3').style.display="block";
	document.getElementById('imgp3').style.display="none";
	document.getElementById('bb4').style.display="block";
	}
	if(val==5)
	{
	document.getElementById('imgm4').style.display="block";
	document.getElementById('imgp4').style.display="none";
	document.getElementById('bb5').style.display="block";
	}
	if(val==6)
	{
	document.getElementById('imgm5').style.display="block";
	document.getElementById('imgp5').style.display="none";
	document.getElementById('bb6').style.display="block";
	}
	if(val==7)
	{
	document.getElementById('imgm6').style.display="block";
	document.getElementById('imgp6').style.display="none";
	document.getElementById('bb7').style.display="block";
	}
	if(val==8)
	{
	document.getElementById('imgm7').style.display="block";
	document.getElementById('imgp7').style.display="none";
	document.getElementById('bb8').style.display="block";
	}
	if(val==9)
	{
	document.getElementById('imgm8').style.display="block";
	document.getElementById('imgp8').style.display="none";
	document.getElementById('bb9').style.display="block";
	}
	if(val==10)
	{
	document.getElementById('imgm9').style.display="block";
	document.getElementById('imgp9').style.display="none";
	document.getElementById('bb10').style.display="block";
	}
	if(val==11)
	{
	document.getElementById('imgm10').style.display="block";
	document.getElementById('imgp10').style.display="none";
	document.getElementById('bb11').style.display="block";
	}
	if(val==12)
	{
	document.getElementById('imgm11').style.display="block";
	document.getElementById('imgp11').style.display="none";
	document.getElementById('bb12').style.display="block";
	}
	if(val==13)
	{
	document.getElementById('imgm12').style.display="block";
	document.getElementById('imgp12').style.display="none";
	document.getElementById('bb13').style.display="block";
	}
	if(val==14)
	{
	document.getElementById('imgm13').style.display="block";
	document.getElementById('imgp13').style.display="none";
	document.getElementById('bb114').style.display="block";
	}
	if(val==15)
	{
	document.getElementById('imgm14').style.display="block";
	document.getElementById('imgp14').style.display="none";
	document.getElementById('bb15').style.display="block";
	}
	if(val==16)
	{
	document.getElementById('imgm15').style.display="block";
	document.getElementById('imgp15').style.display="none";
	document.getElementById('bb16').style.display="block";
	}
	if(val==17)
	{
	document.getElementById('imgm16').style.display="block";
	document.getElementById('imgp16').style.display="none";
	document.getElementById('bb17').style.display="block";
	}
	if(val==18)
	{
	document.getElementById('imgm17').style.display="block";
	document.getElementById('imgp17').style.display="none";
	document.getElementById('bb18').style.display="block";
	}
	if(val==19)
	{
	document.getElementById('imgm18').style.display="block";
	document.getElementById('imgp18').style.display="none";
	document.getElementById('bb19').style.display="block";
	}
	if(val==20)
	{
	document.getElementById('imgm19').style.display="block";
	document.getElementById('imgp19').style.display="none";
	document.getElementById('bb20').style.display="block";
	}
	if(val==21)
	{
	document.getElementById('imgm20').style.display="block";
	document.getElementById('imgp20').style.display="none";
	document.getElementById('bb21').style.display="block";
	}
	if(val==22)
	{
	document.getElementById('imgm21').style.display="block";
	document.getElementById('imgp21').style.display="none";
	document.getElementById('bb22').style.display="block";
	}
	if(val==23)
	{
	document.getElementById('imgm22').style.display="block";
	document.getElementById('imgp22').style.display="none";
	document.getElementById('bb23').style.display="block";
	}
	if(val==24)
	{
	document.getElementById('imgm23').style.display="block";
	document.getElementById('imgp23').style.display="none";
	document.getElementById('bb24').style.display="block";
	}
	if(val==25)
	{
	document.getElementById('imgm24').style.display="block";
	document.getElementById('imgp24').style.display="none";
	document.getElementById('bb25').style.display="block";
	}
	if(val==26)
	{
	document.getElementById('imgm25').style.display="block";
	document.getElementById('imgp25').style.display="none";
	document.getElementById('bb26').style.display="block";
	}
	if(val==27)
	{
	document.getElementById('imgm26').style.display="block";
	document.getElementById('imgp26').style.display="none";
	document.getElementById('bb27').style.display="block";
	}
	if(val==28)
	{
	document.getElementById('imgm27').style.display="block";
	document.getElementById('imgp27').style.display="none";
	document.getElementById('bb28').style.display="block";
	}
	if(val==29)
	{
	document.getElementById('imgm28').style.display="block";
	document.getElementById('imgp28').style.display="none";
	document.getElementById('bb29').style.display="block";
	}
	if(val==30)
	{
	document.getElementById('imgm29').style.display="block";
	document.getElementById('imgp29').style.display="none";
	document.getElementById('bb30').style.display="block";
	}
	if(val==31)
	{
	document.getElementById('imgm30').style.display="block";
	document.getElementById('imgp30').style.display="none";
	document.getElementById('bb31').style.display="block";
	}
	if(val==32)
	{
	document.getElementById('imgm31').style.display="block";
	document.getElementById('imgp31').style.display="none";
	document.getElementById('bb32').style.display="block";
	}
	if(val==33)
	{
	document.getElementById('imgm32').style.display="block";
	document.getElementById('imgp32').style.display="none";
	document.getElementById('bb33').style.display="block";
	}
	if(val==34)
	{
	document.getElementById('imgm33').style.display="block";
	document.getElementById('imgp33').style.display="none";
	document.getElementById('bb34').style.display="block";
	}
	if(val==35)
	{
	document.getElementById('imgm34').style.display="block";
	document.getElementById('imgp34').style.display="none";
	document.getElementById('bb35').style.display="block";
	}
	if(val==36)
	{
	document.getElementById('imgm35').style.display="block";
	document.getElementById('imgp35').style.display="none";
	document.getElementById('bb36').style.display="block";
	}
	if(val==37)
	{
	document.getElementById('imgm36').style.display="block";
	document.getElementById('imgp36').style.display="none";
	document.getElementById('bb37').style.display="block";
	}
	if(val==38)
	{
	document.getElementById('imgm37').style.display="block";
	document.getElementById('imgp37').style.display="none";
	document.getElementById('bb38').style.display="block";
	}
	if(val==39)
	{
	document.getElementById('imgm38').style.display="block";
	document.getElementById('imgp38').style.display="none";
	document.getElementById('bb39').style.display="block";
	}
	if(val==40)
	{
	document.getElementById('imgm39').style.display="block";
	document.getElementById('imgp39').style.display="none";
	document.getElementById('bb40').style.display="block";
	}
	if(val==41)
	{
	document.getElementById('imgm41').style.display="block";
	document.getElementById('imgp41').style.display="none";
	document.getElementById('bb42').style.display="block";
	}
	if(val==42)
	{
	document.getElementById('imgm41').style.display="block";
	document.getElementById('imgp41').style.display="none";
	document.getElementById('bb42').style.display="block";
	}
	if(val==43)
	{
	document.getElementById('imgm42').style.display="block";
	document.getElementById('imgp42').style.display="none";
	document.getElementById('bb43').style.display="block";
	}
	if(val==44)
	{
	document.getElementById('imgm43').style.display="block";
	document.getElementById('imgp43').style.display="none";
	document.getElementById('bb44').style.display="block";
	}
	if(val==45)
	{
	document.getElementById('imgm44').style.display="block";
	document.getElementById('imgp44').style.display="none";
	document.getElementById('bb45').style.display="block";
	}
	if(val==46)
	{
	document.getElementById('imgm45').style.display="block";
	document.getElementById('imgp45').style.display="none";
	document.getElementById('bb46').style.display="block";
	}
	if(val==47)
	{
	document.getElementById('imgm46').style.display="block";
	document.getElementById('imgp46').style.display="none";
	document.getElementById('bb47').style.display="block";
	}
	if(val==48)
	{
	document.getElementById('imgm47').style.display="block";
	document.getElementById('imgp47').style.display="none";
	document.getElementById('bb48').style.display="block";
	}
	if(val==49)
	{
	document.getElementById('imgm48').style.display="block";
	document.getElementById('imgp48').style.display="none";
	document.getElementById('bb49').style.display="block";
	}
	if(val==50)
	{
	document.getElementById('imgm49').style.display="block";
	document.getElementById('imgp49').style.display="none";
	document.getElementById('bb50').style.display="block";
	}
	if(val==51)
	{
	document.getElementById('imgm50').style.display="block";
	document.getElementById('imgp50').style.display="none";
	document.getElementById('bb51').style.display="block";
	}
	if(val==52)
	{
	document.getElementById('imgm51').style.display="block";
	document.getElementById('imgp51').style.display="none";
	document.getElementById('bb52').style.display="block";
	}
	if(val==53)
	{
	document.getElementById('imgm52').style.display="block";
	document.getElementById('imgp52').style.display="none";
	document.getElementById('bb53').style.display="block";
	}
	if(val==54)
	{
	document.getElementById('imgm53').style.display="block";
	document.getElementById('imgp53').style.display="none";
	document.getElementById('bb54').style.display="block";
	}
	if(val==55)
	{
	document.getElementById('imgm54').style.display="block";
	document.getElementById('imgp54').style.display="none";
	document.getElementById('bb55').style.display="block";
	}

}
function hide_block(val)
{
	if(val==1)
		{
		document.getElementById('imgm').style.display="none";
		document.getElementById('imgp').style.display="block";
		document.getElementById('bb1').style.display="none";
		}
	if(val==2)
		{
		document.getElementById('imgm1').style.display="none";
		document.getElementById('imgp1').style.display="block";
		document.getElementById('bb2').style.display="none";
		}
	if(val==3)
		{
		document.getElementById('imgm2').style.display="none";
		document.getElementById('imgp2').style.display="block";
		document.getElementById('bb3').style.display="none";
		}
	if(val==4)
		{
		document.getElementById('imgm3').style.display="none";
		document.getElementById('imgp3').style.display="block";
		document.getElementById('bb4').style.display="none";
		}
	if(val==5)
		{
		document.getElementById('imgm4').style.display="none";
		document.getElementById('imgp4').style.display="block";
		document.getElementById('bb5').style.display="none";
		}
	if(val==6)
		{
		document.getElementById('imgm5').style.display="none";
		document.getElementById('imgp5').style.display="block";
		document.getElementById('bb6').style.display="none";
		}
	if(val==7)
		{
		document.getElementById('imgm6').style.display="none";
		document.getElementById('imgp6').style.display="block";
		document.getElementById('bb7').style.display="none";
		}
	if(val==8)
		{
		document.getElementById('imgm7').style.display="none";
		document.getElementById('imgp7').style.display="block";
		document.getElementById('bb8').style.display="none";
		}
	if(val==9)
		{
		document.getElementById('imgm8').style.display="none";
		document.getElementById('imgp8').style.display="block";
		document.getElementById('bb9').style.display="none";
		}
	if(val==10)
		{
		document.getElementById('imgm9').style.display="none";
		document.getElementById('imgp9').style.display="block";
		document.getElementById('bb10').style.display="none";
		}
		if(val==11)
		{
		document.getElementById('imgm10').style.display="none";
		document.getElementById('imgp10').style.display="block";
		document.getElementById('bb11').style.display="none";
		}
		if(val==12)
		{
		document.getElementById('imgm11').style.display="none";
		document.getElementById('imgp11').style.display="block";
		document.getElementById('bb12').style.display="none";
		}
		if(val==13)
		{
		document.getElementById('imgm12').style.display="none";
		document.getElementById('imgp12').style.display="block";
		document.getElementById('bb13').style.display="none";
		}
		if(val==14)
		{
		document.getElementById('imgm13').style.display="none";
		document.getElementById('imgp13').style.display="block";
		document.getElementById('bb14').style.display="none";
		}
		if(val==15)
		{
		document.getElementById('imgm14').style.display="none";
		document.getElementById('imgp14').style.display="block";
		document.getElementById('bb15').style.display="none";
		}
		if(val==16)
		{
		document.getElementById('imgm15').style.display="none";
		document.getElementById('imgp15').style.display="block";
		document.getElementById('bb16').style.display="none";
		}
		if(val==17)
		{
		document.getElementById('imgm16').style.display="none";
		document.getElementById('imgp16').style.display="block";
		document.getElementById('bb17').style.display="none";
		}
		if(val==18)
		{
		document.getElementById('imgm17').style.display="none";
		document.getElementById('imgp17').style.display="block";
		document.getElementById('bb18').style.display="none";
		}
		if(val==19)
		{
		document.getElementById('imgm18').style.display="none";
		document.getElementById('imgp18').style.display="block";
		document.getElementById('bb19').style.display="none";
		}
		if(val==20)
		{
		document.getElementById('imgm19').style.display="none";
		document.getElementById('imgp19').style.display="block";
		document.getElementById('bb20').style.display="none";
		}
		if(val==21)
		{
		document.getElementById('imgm20').style.display="none";
		document.getElementById('imgp20').style.display="block";
		document.getElementById('bb21').style.display="none";
		}
		if(val==22)
		{
		document.getElementById('imgm21').style.display="none";
		document.getElementById('imgp21').style.display="block";
		document.getElementById('bb22').style.display="none";
		}
		if(val==23)
		{
		document.getElementById('imgm22').style.display="none";
		document.getElementById('imgp22').style.display="block";
		document.getElementById('bb23').style.display="none";
		}
		if(val==24)
		{
		document.getElementById('imgm23').style.display="none";
		document.getElementById('imgp23').style.display="block";
		document.getElementById('bb24').style.display="none";
		}
		if(val==25)
		{
		document.getElementById('imgm24').style.display="none";
		document.getElementById('imgp24').style.display="block";
		document.getElementById('bb25').style.display="none";
		}
		if(val==26)
		{
		document.getElementById('imgm25').style.display="none";
		document.getElementById('imgp25').style.display="block";
		document.getElementById('bb26').style.display="none";
		}
		if(val==27)
		{
		document.getElementById('imgm26').style.display="none";
		document.getElementById('imgp26').style.display="block";
		document.getElementById('bb27').style.display="none";
		}
		if(val==28)
		{
		document.getElementById('imgm27').style.display="none";
		document.getElementById('imgp27').style.display="block";
		document.getElementById('bb28').style.display="none";
		}
		if(val==29)
		{
		document.getElementById('imgm28').style.display="none";
		document.getElementById('imgp28').style.display="block";
		document.getElementById('bb29').style.display="none";
		}
		if(val==30)
		{
		document.getElementById('imgm29').style.display="none";
		document.getElementById('imgp29').style.display="block";
		document.getElementById('bb30').style.display="none";
		}
		if(val==31)
		{
		document.getElementById('imgm30').style.display="none";
		document.getElementById('imgp30').style.display="block";
		document.getElementById('bb31').style.display="none";
		}
		if(val==32)
		{
		document.getElementById('imgm31').style.display="none";
		document.getElementById('imgp31').style.display="block";
		document.getElementById('bb32').style.display="none";
		}
		if(val==33)
		{
		document.getElementById('imgm32').style.display="none";
		document.getElementById('imgp32').style.display="block";
		document.getElementById('bb33').style.display="none";
		}
		if(val==34)
		{
		document.getElementById('imgm33').style.display="none";
		document.getElementById('imgp33').style.display="block";
		document.getElementById('bb34').style.display="none";
		}
		if(val==35)
		{
		document.getElementById('imgm34').style.display="none";
		document.getElementById('imgp34').style.display="block";
		document.getElementById('bb35').style.display="none";
		}
		if(val==36)
		{
		document.getElementById('imgm35').style.display="none";
		document.getElementById('imgp35').style.display="block";
		document.getElementById('bb36').style.display="none";
		}
		if(val==37)
		{
		document.getElementById('imgm36').style.display="none";
		document.getElementById('imgp36').style.display="block";
		document.getElementById('bb37').style.display="none";
		}
		if(val==38)
		{
		document.getElementById('imgm37').style.display="none";
		document.getElementById('imgp37').style.display="block";
		document.getElementById('bb38').style.display="none";
		}
		if(val==39)
		{
		document.getElementById('imgm38').style.display="none";
		document.getElementById('imgp38').style.display="block";
		document.getElementById('bb39').style.display="none";
		}
		if(val==40)
		{
		document.getElementById('imgm39').style.display="none";
		document.getElementById('imgp39').style.display="block";
		document.getElementById('bb40').style.display="none";
		}
		if(val==41)
		{
		document.getElementById('imgm40').style.display="none";
		document.getElementById('imgp40').style.display="block";
		document.getElementById('bb42').style.display="none";
		}
		if(val==42)
		{
		document.getElementById('imgm41').style.display="none";
		document.getElementById('imgp41').style.display="block";
		document.getElementById('bb42').style.display="none";
		}
		if(val==43)
		{
		document.getElementById('imgm42').style.display="none";
		document.getElementById('imgp42').style.display="block";
		document.getElementById('bb43').style.display="none";
		}
		if(val==44)
		{
		document.getElementById('imgm43').style.display="none";
		document.getElementById('imgp43').style.display="block";
		document.getElementById('bb44').style.display="none";
		}
		if(val==45)
		{
		document.getElementById('imgm44').style.display="none";
		document.getElementById('imgp44').style.display="block";
		document.getElementById('bb45').style.display="none";
		}
		if(val==46)
		{
		document.getElementById('imgm45').style.display="none";
		document.getElementById('imgp45').style.display="block";
		document.getElementById('bb46').style.display="none";
		}
		if(val==47)
		{
		document.getElementById('imgm46').style.display="none";
		document.getElementById('imgp46').style.display="block";
		document.getElementById('bb47').style.display="none";
		}
		if(val==48)
		{
		document.getElementById('imgm47').style.display="none";
		document.getElementById('imgp47').style.display="block";
		document.getElementById('bb48').style.display="none";
		}
		if(val==49)
		{
		document.getElementById('imgm48').style.display="none";
		document.getElementById('imgp48').style.display="block";
		document.getElementById('bb49').style.display="none";
		}
		if(val==50)
		{
		document.getElementById('imgm49').style.display="none";
		document.getElementById('imgp49').style.display="block";
		document.getElementById('bb50').style.display="none";
		}
		if(val==51)
		{
		document.getElementById('imgm50').style.display="none";
		document.getElementById('imgp50').style.display="block";
		document.getElementById('bb51').style.display="none";
		}
		if(val==52)
		{
		document.getElementById('imgm51').style.display="none";
		document.getElementById('imgp51').style.display="block";
		document.getElementById('bb52').style.display="none";
		}
		if(val==53)
		{
		document.getElementById('imgm52').style.display="none";
		document.getElementById('imgp52').style.display="block";
		document.getElementById('bb53').style.display="none";
		}
		if(val==54)
		{
		document.getElementById('imgm53').style.display="none";
		document.getElementById('imgp53').style.display="block";
		document.getElementById('bb54').style.display="none";
		}
		if(val==55)
		{
		document.getElementById('imgm54').style.display="none";
		document.getElementById('imgp54').style.display="block";
		document.getElementById('bb55').style.display="none";
		}

}
