package com.pay10.isgpay;

public class Constants {
	
	public static final String SEPARATOR = "::";
	public static final String REFUND_SEPARATOR = "&";
	public static final String EQUATOR = "||";
	public static final String ORDER_INFO = "OrderInfo";
	public static final String URL = "URL";
	public static final String TXN_TYPE = "TxnType";
	public static final String TXN_REF_NO = "TxnRefNo";
	public static final String MERCHANT_ID = "MerchantId";
	public static final String PASS_CODE = "PassCode";
	public static final String AMOUNT = "Amount";
	public static final String TERMINAL_ID = "TerminalId";
	public static final String MCC = "MCC";
	public static final String RETURN_URL = "ReturnURL";
	public static final String CARD_NUMBER = "CardNumber";
	public static final String EXPIRY_DATE = "ExpiryDate";
	public static final String CVV = "CardSecurityCode";
	public static final String VPA = "VPA";
	public static final String BANK_CODE = "BankCode";
	public static final String VERSION = "Version";
	public static final String HASH = "SecureHash";
	public static final String ENCDATA = "EncData";
	public static final String RET_REF_NO = "RetRefNo";
	public static final String REFUND_AMOUNT = "RefundAmount";
	public static final String REF_CANCEL_ID = "RefCancelID";
	public static final String SALE_TXN_TYPE_CODE = "01";
	public static final String REFUND_TXN_TYPE_CODE = "04";
	public static final String STATUS_ENQUIRY_TXN_TYPE_CODE = "05";
	public static final String SALE_RETURN_URL = "ISGPAYReturnUrl";
	public static final String REFUND_REQUEST_URL = "ISGPAYRefundUrl";
	public static final String STATUS_ENQ_REQUEST_URL = "ISGPAYStatusEnqUrl";
	public static final String RESPONSE_CODE = "ResponseCode";
	public static final String RESPONSE_CODE_VALUE = "00";
	public static final String AUTH_CODE = "AuthCode";
	public static final String MESSAGE = "Message";
	public static final String MERCHANT_NAME = "MerchantName";
	public static final String MERCHANT_CITY = "MerchantCity";
	public static final String MERCHANT_STATE = "MerchantState";
	public static final String MERCHANT_POSTAL_CODE = "MerchPostalCode";
	public static final String MERCHANT_PHONE = "MerchPhone";
	public static final String CURRENCY = "Currency";
	public static final String MERCHANT_NAME_VALUE = "PayTen";
	public static final String MERCHANT_CITY_VALUE = "DELHI";
	public static final String MERCHANT_STATE_VALLUE = "DL";
	public static final String MERCHANT_POSTAL_CODE_VALUE = "110001";
	public static final String MERCHANT_PHONE_VALUE = "9879879879";
	public static final String ZERO_VALUE = "0";
	public static final String STATUS = "Status";
	public static final String PAY_OPT = "payOpt";
	public static final String PAY_OPT_CC_VAL = "cc";
	public static final String PAY_OPT_DC_VAL = "dc";
	public static final String PAY_OPT_NB_VAL = "nb";
	public static final String PAY_OPT_UPI_VAL = "upi";
	public static final Object ISGPAY_RETURN_URL = "ISGPAYReturnUrl";
	public static final String ISGPAY_TXN_TYPE_PAY_VALUE = "Pay";
	public static final String BANK_ID = "BankId";
	public static final Object ISGPAY_REFUND_URL = "ISGPAYRefundUrl";
	public static final Object ISGPAY_STATUS_ENQ_URL = "ISGPAYStatusEnqUrl";
	
	public static final Object SELECT_MID_FOR_RUPAY	= "selectMidForRupay";
}
