package com.pay10.kotak.upi;

public class Constants {
	public static final String EQUATOR = "=";
	public static final String SEPARATOR = "&";
	public static final String GRANDTYPE = "grant_type";
	public static final String CLIENTID = "client_id";
    public static final String CLIENTSECRET = "client_secret";
    public static final String CUSTOMERID = "customerId";
    public static final String AGGREGATORID = "aggregatorId";
    public static final String VPA = "vpa";
    public static final String ACCESS_TOKEN = "access_token";
    public static final String CODE = "code";
    public static final String PAYER_ADDRESS = "payerAddress";
    public static final String AMT = "amount";
    public static final String ORDERID = "orderId";
    public static final String PAYERVPA = "payerVpa";
    public static final String REMARKS = "remarks";
    public static final String TXNID = "txnId";
    public static final String AGGREGATORVPA = "aggregatorVPA";
    public static final String EXPIRY= "expiry";
    public static final String TIMESTAMP= "timeStamp";
    public static final String MRC= "merchantReferenceCode";
    public static final String APP= "app";
    public static final String APPVALUE= "KotakUpiAppValue";
    public static final String MOBILE= "mobile";
    public static final String ACCHN= "accounholdername";
    public static final String ACCREFN= "accrefnumber";
    public static final String ACCTYPE= "acctype";
    public static final String PAYEEVPA = "PayeeVPA";
    public static final String MCC= "mcc";
    public static final String IFSC = "ifsc";
    public static final String MERCHANTREFID = "merchantrefid";
    public static final String MERCHANTID = "merchantId";
    public static final String DEVICEDETAILS = "deviceDetails";
    public static final String DEBITACCOUNT = "debitAccount";
    public static final String APPROVALREF = "approvalRef";
    public static final String CUSTOMEREFID = "customerefid";
    public static final String CAPABILITY = "capability";
    public static final String GCMID = "gcmid";
    public static final String GCMIDVALUE = "23243454355654";
    public static final String GEOCODE = "geocode";
    public static final String GEOCODEVALUE = "12.02,17.03";
    public static final String ID = "id";
    public static final String IDVALUE = "91323234234234";
    public static final String IP = "ip";
    public static final String IPVALUE = "127.0.0.1";
    public static final String CAPABILITYVALUE = "1111";
    public static final String LOCATION = "location";
    public static final String LOCATIONVALUE = "Delhi";
    public static final String OS = "os";
    public static final String OSVALUE = "Android";
    public static final String TYPE = "type";
    public static final String TYPEVALUE = "motox";
    public static final String REFID = "refId";
    public static final String REFURL = "refUrl";
    public static final String JSON = " ";
    public static final String DEVICE = "deviceDetails";
    public static final String TRNSINITIATED = "noRemark"; 
    public static final String DATEFORMAT = "yyyy-MM-ddHH:mm:ss";
    public static final String EXPIRYTIME = "KotakUpiExpiryTime";
    public static final String CLIENTCREDENTIAL = "clientCredential";
    public static final String SUCCESS_RESPONSE = "00";
    public static final String SUCCESS_RESPONSE_MSG = "result";
    
}
