paymentgateway.demo:
  ############################# URL Start ###############################
  statusEnquiryApiUrl: http://127.0.0.1:8080/pgws/enquiry/process
  refundApiUrl: http://127.0.0.1:8080/pgws/enquiry/internalRefund
  #############################  URL End ################################
  ############################  MONGO_DB  ###############################
  MONGO_DB_host: 127.0.0.1
  MONGO_DB_port: 27017
  MONGO_DB_dbName: pay10
  MONGO_DB_mongoURIprefix: "mongodb://"
  MONGO_DB_mongoURIsuffix: "@localhost:27017/pay10?maxPoolSize=1000&minPoolSize=100"
  MONGO_DB_username: root
  MONGO_DB_password: VsP8sdyhKwuWnVUi0AOocw==
  MONGO_DB_collectionName: transaction
  MONGO_DB_schedulerLogsCollection: schedulerLogs
  MONGO_DB_statusEnquiryCollectionName: transactionStatus

  ########################################################################
  
    ################### Transaction Status Enquiry Start ################
  transactionStatusEnquiry: 1
  acquirerName: YESBANKCB,ATOM,FREECHARGE,PAYU,SBI,CASHFREE,AXIS,DEMO
  #transactionBankStatusEnquiryCron: 0 0/1 * 1/1 * ? *
  transactionBankStatusEnquiryCron: 0/10 * * * * ?
  merchantPayId: ALL
  minutesBefore: 1
  minutesInterval: 10
  minutesBeforePayout: 1
  minutesBeforePayoutEnquiry: 1
  minutesIntervalPayoutEnquiry: 250
  salePayoutUrl: http://localhost:8080/pgws/payout/transact
  enquiryApiUrl: http://127.0.0.1:8080/pgws/enquiry/process
  payuStatusEnquiryApiUrl: http://localhost:8080/pgws/enquiry/payoutProcess
  
  webhookFailedCount: 3
  webhookPayInResponseFields: CUST_NAME,TXNTYPE,PAY_TYPE,AMOUNT,CURRENCY_CODE,ORDER_ID,PAY_ID,PAYMENT_TYPE,MOP_TYPE,CARD_MASK,PG_REF_NUM,RESPONSE_CODE,RESPONSE_MESSAGE,STATUS,HASH,RRN,ACQ_ID,CUST_EMAIL,CUST_PHONE,PG_TXN_MESSAGE,RETURN_URL,RESPONSE_DATE_TIME,PRODUCT_DESC,CARD_ISSUER_BANK,CARD_ISSUER_COUNTRY,TOTAL_AMOUNT
  webhookPayOutResponseFields: RESPONSE_CODE,PAY_TYPE,CUST_PHONE,ACC_CITY_NAME,ACC_NAME,REMARKS,CURRENCY_CODE,IFSC,STATUS,ACC_NO,PG_REF_NO,AMOUNT,RESPONSE_MESSAGE,CUST_EMAIL,PAY_ID,ORDER_ID,HASH
  webhookEnable: N
  ################### Transaction Status Enquiry End ################
  
  
server:
  port: 8092
  servlet:
    context-path: /schedular
 
spring:
  datasource:
    driver-class-name: "com.mysql.jdbc.Driver"
    username: "root"
    url: "jdbc:mysql://localhost:3306/pay10?autoReconnect=true&amp;useSSL=false"
    password: "123456" 