paymentgateway.demo:
  ############################# URL Start ###############################
  statusEnquiryApiUrl: https://uat.pay10.com/pgws/enquiry/process
  refundApiUrl: https://uat.pay10.com/pgws/enquiry/internalRefund
  #############################  URL End ################################
  ############################  MONGO_DB  ###############################
  MONGO_DB_host: 172.16.2.16
  MONGO_DB_port: 27017
  MONGO_DB_dbName: pay10
  MONGO_DB_mongoURIprefix: "mongodb://"
  MONGO_DB_mongoURIsuffix: "@172.16.2.16:27017/pay10?maxPoolSize=1000&minPoolSize=100"
  MONGO_DB_username: root
  MONGO_DB_password: root123
  MONGO_DB_collectionName: transaction
  MONGO_DB_schedulerLogsCollection: schedulerLogs

  ########################################################################
  
    ################### Transaction Status Enquiry Start ################
  transactionStatusEnquiry: 1
  acquirerName: YESBANKCB,ATOM,FREECHARGE,PAYU,CASHFREE,SBI
  #transactionBankStatusEnquiryCron: 0 0/1 * 1/1 * ? *
  transactionBankStatusEnquiryCron: 0/10 * * * * ?
  merchantPayId: ALL
  minutesBefore: 1
  minutesInterval: 100
  enquiryApiUrl: https://uat.pay10.com/pgws/enquiry/process
  ################### Transaction Status Enquiry End ################
  
  ################### Reseller scheduler Start ################
  commissionSchedulerApiUrl: https://preprod.pay10.com/pgws/schuldar/process
  resellerMonthlyPayoutSchedulerApiUrl: https://preprod.pay10.com/pgws/schuldar/payout
  resellerQuaterlyPayoutSchedulerApiUrl: https://preprod.pay10.com/pgws/schuldar/payoutmonth
  ################### Reseller scheduler End ################
  
  
server:
  port: 8092
  servlet:
    context-path: /schedular