package com.pay10.paytm;


public enum PaytmResultType {
	
	PAYTM000			("10" , "000" , "SUCCESS" , "Refund successful"),
	PAYTM001			("601" , "000" , "SUCCESS" , "Refund request was raised for this transaction. But it is pending state"),
	PAYTM002			("328" , "007" , "Rejected" , "Currency not same"),
	PAYTM003			("501" , "022" , "Failed at Acquirer" , "System error"),
	PAYTM004			("600" , "013" , "Declined" , "Invalid refund request"),
	PAYTM005			("606" , "007" , "Rejected" , "Checksum generated by Paytm payment gateway does not match checksum expected by bank"),
	PAYTM006			("607" , "004" , "Declined" , "Order not exist for current request"),
	PAYTM007			("609" , "007" , "Rejected" , "Refund initiated for a rejected transaction"),
	PAYTM008			("612" , "007" , "Rejected" , "This is a valid authorized transaction"),
	PAYTM009			("617" , "013" , "Declined" , "Refund already raised"),
	PAYTM010			("619" , "013" , "Declined"  , "Invalid refund amount"),
	PAYTM011			("620" ,"022" , "Failed at Acquirer" , "Refund failed"),
	PAYTM012			("622" , "022" , "Failed at acquirer" , "Something went wrong."),
	PAYTM013			("635" , "013" , "Declined" , "Partial Refund under Rupee 1 is not allowed"),
	PAYTM014			("640" , "013" , "Declined" , "Order is frozen."),
	PAYTM015			("700" , "007" , "Rejected" , "Invalid consult request."),
	PAYTM016			("701" , "013" , "Declined" , "Refund already raised with same refid."),
	PAYTM017			("702" , "013" , "Declined"  , "Not allowed to reprocess refund request."),
	PAYTM018			("703" , "013" , "Declined" , "Refund is already success or in pending state. Please check status query for final result."),
	PAYTM019			("704" , "007" , "Rejected" , "Balance not enough."),
	
	PAYTM020			("01" ,  "000" , "SUCCESS" , "Txn Success"),
	PAYTM021			("227" , "013" , "Declined" , "Your payment has been declined by your bank. Please contact your bank for any queries."),
	PAYTM022			("235" , "013" , "Declined" , "Wallet balance Insufficient."),
	PAYTM023			("295" , "013" , "Declined" , "Your payment failed as the UPI ID entered is incorrect."),
	PAYTM024			("334" , "007" , "Rejected" , "Invalid Order ID."),
	PAYTM025			("400" , "028" , "Pending at Acquirer" , "Transaction status not confirmed yet."),
	PAYTM026			("401" , "013" , "Declined" , "Your payment has been declined by your bank. Please contact your bank for any queries."),
	PAYTM027			("402" , "028" , "Pending at Acquirer" , "Looks like the payment is not complete. Please wait while we confirm the status with your bank."),
	PAYTM028			("810" , "022" , "Failed at acquirer" , "Txn Failed."),
	
	PAYTM029			("501" ,  "028" , "Pending at Acquirer" , "System error"),
	PAYTM030			("604" , "013" , "Declined" , "We are experiencing delays from the bank."),
	PAYTM031			("311" , "013" , "Declined" , "Invalid refund request"),
	PAYTM032			("331" , "013" , "Declined" , "Record not found."),
	PAYTM033			("602" , "013" , "Declined" , "Bank has declined refund request."),
	PAYTM034			("610" , "013" , "Declined" , "	Transaction fully refunded already."),
	PAYTM035			("401" , "013" , "Declined" , "Your payment has been declined by your bank. Please contact your bank for any queries."),
	PAYTM036			("402" , "028" , "Pending at Acquirer" , "Looks like the payment is not complete. Please wait while we confirm the status with your bank."),
	PAYTM037			("623" ,  "013" , "Declined" , "Refund is already Success or in Pending state.Please check status query for final result"),
	PAYTM038			("141" ,  "010","Cancelled" , "User has not completed transaction."),;
	
	private PaytmResultType(String bankCode, String iPayCode, String statusCode, String message) {
		this.bankCode = bankCode;
		this.iPayCode = iPayCode;
		this.statusCode = statusCode;
		this.message = message;
	}

	public static PaytmResultType getInstanceFromName(String code) {
		PaytmResultType[] statusTypes = PaytmResultType.values();
		for (PaytmResultType statusType : statusTypes) {
			if (String.valueOf(statusType.getBankCode()).toUpperCase().equals(code)) {
				return statusType;
			}
		}
		return null;
	}

	private final String bankCode;
	private final String iPayCode;
	private final String statusCode;
	private final String message;

	public String getBankCode() {
		return bankCode;
	}

	public String getiPayCode() {
		return iPayCode;
	}

	public String getStatusCode() {
		return statusCode;
	}

	public String getMessage() {
		return message;
	}
}