package com.pay10.pg.core.util;

public class ConstantsGPay {
	public static final String GOOGLEMERCHANTID = "googleMerchantId";
	public static final String MERCHANTTRANSACTIONID = "merchantTransactionId";
	public static final String TRANSACTIONIDENTIFIER = "transactionIdentifier";
	public static final String MOBILENO = "phoneNumber";
	public static final String  TXNID = "transactionId";
	public static final String CURRENCYCODE = "currencyCode";
	public static final String UNITS = "units";
	public static final String NANOS = "nanos";
	public static final String AMOUNTPAYABLE = "amountPayable";
	public static final String MERCHANTINFO = "merchantInfo";
	public static final String USERINFO = "userInfo";
	public static final String MERCHANTTXNDETAIL = "merchantTransactionDetails";
	public static final String DESCRIPTION = "description";
	public static final String ORIGINATINGPLATFORM = "originatingPlatform";
	public static final String GOOGLEPAY_SCOPE_URL = "googlePayscopeUrl";
	public static final String GOOGLEPAY_TOKEN_URL = "googlePayTokenUrl";
	public static final String PG_PROPERTIES_PATH = "BPGATE_PROPS";
	public static final String JWT_FILE_NAME = "IRCTCIPAY-e376c712da36.json";
	public static final String GOOGLEPAY_PUSH_NOTIFICATION_URL ="googlePayPushNotificationUrl";
	public static final String SAMPLE_DESCRIPTION ="Sample description";
	public static final String DESKTOP = "DESKTOP";
	public static final String ACCESS_TOKEN = "access_token";
	public static final String ERROR_RESPONSE_CODE = "400";
	public static final String VPAINVALID = "invalidVpa";
	public static final String VPAMSG = "please enter valid vpa";
	public static final String SPLIT = "\\.";
	public static final String ZERO = "0";
	public static final String TOKEN_FAILURE = "token not generated";
	public static final String GOOGLEPAY_TRANSACTION_STATUS_URL ="googlePayTransactionDetail";
	public static final String TXNSTATUS = "transactionStatus";
	public static final String STATUS = "status";
	public static final String FAIL = "FAILURE";
	public static final String IN_PROGRESS = "IN_PROGRESS";
	public static final String PAYMENT_NOT_INITIATED = "PAYMENT_NOT_INITIATED";
	public static final String DECLINED = "DECLINED";
	public static final String EXPIRED = "EXPIRED";
	public static final String TIME = "lastUpdatedTime";
	public static final String GPAYTXNID = "googleTransactionId";
	public static final String GPAYSTATUS = "Processing";
	public static final String SUCCESS = "SUCCESS";
	public static final String CAPTURED = "Captured";
}
