################ TRANSACTION TABLE #####################
CREATE TABLE `TRANSACTION` (
  `CARD_MASK` varchar(50) DEFAULT NULL,
  `TXN_ID` bigint(16) NOT NULL,
  `OID` bigint(16) DEFAULT NULL,
  `ORIG_TXN_ID` bigint(16) DEFAULT NULL,
  `TXNTYPE` varchar(50) DEFAULT NULL,
  `AMOUNT` decimal(12,2) DEFAULT NULL,
  `ORDER_ID` varchar(250) DEFAULT NULL,
  `CUST_NAME` varchar(250) DEFAULT NULL,
  `PAY_ID` varchar(250) DEFAULT NULL,
  `ACCT_ID` bigint(20) DEFAULT NULL,
  `MOP_TYPE` char(4) DEFAULT NULL,
  `PAYMENT_TYPE` char(2) DEFAULT NULL,
  `CURRENCY_CODE` char(3) DEFAULT NULL,
  `STATUS` varchar(50) DEFAULT NULL,
  `RESPONSE_CODE` varchar(50) DEFAULT NULL,
  `RESPONSE_MESSAGE` varchar(512) DEFAULT NULL,
  `CREATE_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ACQ_ID` varchar(256) DEFAULT NULL,
  `CUST_EMAIL` varchar(256) DEFAULT NULL,
  `INTERNAL_CUST_IP` varchar(256) DEFAULT NULL,
  `RRN`	varchar(256) DEFAULT NULL,
  `PG_REF_NUM` varchar(256) DEFAULT NULL,
  `AUTH_CODE` char(12) DEFAULT NULL,
  `PG_RESP_CODE` varchar(256) DEFAULT NULL,
  `PG_TXN_MESSAGE` varchar(256) DEFAULT NULL,
  `PG_TXN_STATUS` varchar(256) DEFAULT NULL,
  `PG_DATE_TIME` varchar(256) DEFAULT NULL,
  `PG_GATEWAY` varchar(256) DEFAULT NULL,
  `ACQUIRER_TYPE` char(15) DEFAULT NULL,
  `PRODUCT_DESC` varchar(1024) DEFAULT NULL,
  `INTERNAL_REQUEST_FIELDS` BLOB(6000) DEFAULT NULL,
  `INTERNAL_CUST_COUNTRY_NAME` varchar(256) DEFAULT NULL,
  `INTERNAL_TXN_AUTHENTICATION` varchar(256) DEFAULT NULL,
  `INTERNAL_CARD_ISSUER_BANK` varchar(256) DEFAULT NULL,
  `INTERNAL_CARD_ISSUER_COUNTRY` varchar(256) DEFAULT NULL,
  `INTERNAL_USER_EMAIL` varchar(256) DEFAULT NULL,  
  `IS_RECURRING` varchar(1) DEFAULT NULL,
  `RECURRING_TRANSACTION_INTERVAL` varchar(25) DEFAULT NULL,
  `RECURRING_TRANSACTION_COUNT` varchar(2) DEFAULT NULL,
  `SURCHARGE_AMOUNT` decimal(12,2) DEFAULT NULL,
  `SURCHARGE_FLAG` varchar(1) DEFAULT NULL,
   `INTERNAL_TXN_CHANNEL` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`TXN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE INDEX order_id_index ON TRANSACTION (ORDER_ID) USING hash;
CREATE INDEX txn_id_index ON TRANSACTION (TXN_ID) USING hash;
CREATE INDEX pay_id_index ON TRANSACTION (PAY_ID) USING btree;
CREATE INDEX txntype_index ON TRANSACTION (TXNTYPE) USING hash;
CREATE INDEX status_index ON TRANSACTION (STATUS) USING hash;
CREATE INDEX create_date_index ON TRANSACTION (CREATE_DATE) USING hash;
CREATE INDEX orig_txn_id_index ON TRANSACTION (ORIG_TXN_ID)  USING hash;
################ TRANSACTION TABLE#####################

######################## KEY TABLE#####################
CREATE TABLE `KEY_STORE` (
  `KEY_ID` int(11) NOT NULL,
  `KEY_NAME` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`KEY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
####################### KEY TABLE#####################

################ BILLING DETAILS #####################
CREATE TABLE `BILLING_DETAILS` (
  `TXN_ID` bigint(16) NOT NULL,
  `ORDER_ID` varchar(250) DEFAULT NULL,
  `CREATE_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
  `CUST_ID` varchar(250) DEFAULT NULL,
  `CUST_NAME` varchar(250) DEFAULT NULL,
  `CUST_PHONE` varchar(250) DEFAULT NULL,
  `CUST_EMAIL` varchar(250) DEFAULT NULL,
  `CUST_STREET_ADDRESS1` varchar(250) DEFAULT NULL,
  `CUST_STREET_ADDRESS2` varchar(250) DEFAULT NULL,
  `CUST_CITY` varchar(250) DEFAULT NULL,
  `CUST_STATE` varchar(250) DEFAULT NULL,
  `CUST_COUNTRY` varchar(250) DEFAULT NULL,
  `CUST_ZIP` varchar(250) DEFAULT NULL,   
  `CUST_FIRST_NAME` varchar(250) DEFAULT NULL,
  `CUST_LAST_NAME` varchar(250) DEFAULT NULL,
  
  `CUST_SHIP_NAME` varchar(250) DEFAULT NULL,
  `CUST_SHIP_PHONE` varchar(250) DEFAULT NULL,
  `CUST_SHIP_EMAIL` varchar(250) DEFAULT NULL,
  `CUST_SHIP_STREET_ADDRESS1` varchar(250) DEFAULT NULL,
  `CUST_SHIP_STREET_ADDRESS2` varchar(250) DEFAULT NULL,
  `CUST_SHIP_CITY` varchar(250) DEFAULT NULL,
  `CUST_SHIP_STATE` varchar(250) DEFAULT NULL,
  `CUST_SHIP_COUNTRY` varchar(250) DEFAULT NULL,
  `CUST_SHIP_ZIP` varchar(250) DEFAULT NULL,   
  `CUST_SHIP_FIRST_NAME` varchar(250) DEFAULT NULL,
  `CUST_SHIP_LAST_NAME` varchar(250) DEFAULT NULL,  
    PRIMARY KEY (`TXN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE INDEX txn_id_index ON BILLING_DETAILS (TXN_ID) USING hash;
################ BILLING DETAILS #####################
